# Code generated by e2e-generator. DO NOT EDIT.

defmodule E2eTests.IntelTest do
  use ExUnit.Case, async: true

  @tag :skip_unless_python
  test "python_chunking_intel" do
    # Intel: chunk multi-function Python source into multiple pieces
    unless TreeSitterLanguagePack.has_language("python") do
      IO.puts("Skipping: language 'python' not available")
    else
    result_json = TreeSitterLanguagePack.process_and_chunk("def alpha():\n    pass\n\ndef beta():\n    pass\n\ndef gamma():\n    pass\n\ndef delta():\n    pass\n", "python", 30)
    result = Jason.decode!(result_json)
    intel = result["intelligence"]
    chunks = result["chunks"]
    assert intel["language"] == "python"
    assert intel["metrics"]["total_lines"] >= 8
    assert length(chunks) >= 2
    end
  end

  @tag :skip_unless_python
  test "python_function_intel" do
    # Intel: extract structure from Python function definition
    unless TreeSitterLanguagePack.has_language("python") do
      IO.puts("Skipping: language 'python' not available")
    else
    result_json = TreeSitterLanguagePack.process("def greet(name):\n    return f'Hello, {name}!'\n", "python")
    intel = Jason.decode!(result_json)
    assert intel["language"] == "python"
    assert length(intel["structure"]) >= 1
    assert Enum.any?(intel["structure"], fn s -> s["kind"] == "function" end)
    assert intel["metrics"]["total_lines"] >= 2
    assert intel["metrics"]["error_count"] == 0
    end
  end

  @tag :skip_unless_rust
  test "rust_function_intel" do
    # Intel: extract structure from Rust function definition
    unless TreeSitterLanguagePack.has_language("rust") do
      IO.puts("Skipping: language 'rust' not available")
    else
    result_json = TreeSitterLanguagePack.process("fn add(a: i32, b: i32) -> i32 {\n    a + b\n}\n", "rust")
    intel = Jason.decode!(result_json)
    assert intel["language"] == "rust"
    assert length(intel["structure"]) >= 1
    assert Enum.any?(intel["structure"], fn s -> s["kind"] == "function" end)
    assert intel["metrics"]["total_lines"] >= 3
    assert intel["metrics"]["error_count"] == 0
    end
  end

end
