// Code generated by e2e-generator. DO NOT EDIT.

package io.github.treesitter.languagepack.e2e;

import static org.junit.jupiter.api.Assertions.*;

import io.github.treesitter.languagepack.TsPackRegistry;
import org.junit.jupiter.api.Test;

import com.google.gson.Gson;
import com.google.gson.JsonObject;
import com.google.gson.JsonArray;

class IntelTest {

    private static final Gson GSON = new Gson();

    @Test
    void python_chunking_intel() {
        // Intel: chunk multi-function Python source into multiple pieces
        try (var registry = Helpers.createRegistry()) {
            org.junit.jupiter.api.Assumptions.assumeTrue(registry.hasLanguage("python"), "Language 'python' not available");
        }
        try (var registry = Helpers.createRegistry()) {
            String resultJson = registry.processAndChunk("def alpha():\n    pass\n\ndef beta():\n    pass\n\ndef gamma():\n    pass\n\ndef delta():\n    pass\n", "python", 30);
            JsonObject intel = GSON.fromJson(resultJson, JsonObject.class);
            JsonArray chunks = intel.getAsJsonArray("chunks");
            assertTrue(chunks.size() >= 2, "Should have at least 2 chunk(s), got " + chunks.size());
            intel = intel.getAsJsonObject("intelligence");
            assertEquals("python", intel.get("language").getAsString());
            JsonObject metrics = intel.getAsJsonObject("metrics");
            assertTrue(metrics.get("total_lines").getAsInt() >= 8, "Should have at least 8 total line(s)");
        }
    }

    @Test
    void python_function_intel() {
        // Intel: extract structure from Python function definition
        try (var registry = Helpers.createRegistry()) {
            org.junit.jupiter.api.Assumptions.assumeTrue(registry.hasLanguage("python"), "Language 'python' not available");
        }
        try (var registry = Helpers.createRegistry()) {
            String resultJson = registry.process("def greet(name):\n    return f'Hello, {name}!'\n", "python");
            JsonObject intel = GSON.fromJson(resultJson, JsonObject.class);
            assertEquals("python", intel.get("language").getAsString());
            assertTrue(intel.getAsJsonArray("structure").size() >= 1, "Should have at least 1 structure(s)");
            boolean foundKind = false;
            for (var elem : intel.getAsJsonArray("structure")) {
                if (elem.getAsJsonObject().get("kind").getAsString().equals("function")) {
                    foundKind = true;
                    break;
                }
            }
            assertTrue(foundKind, "Structure should contain a 'function' kind node");
            JsonObject metrics = intel.getAsJsonObject("metrics");
            assertTrue(metrics.get("total_lines").getAsInt() >= 2, "Should have at least 2 total line(s)");
            JsonObject metricsObj = intel.getAsJsonObject("metrics");
            assertEquals(0, metricsObj.get("error_count").getAsInt(), "Expected error_count 0");
        }
    }

    @Test
    void rust_function_intel() {
        // Intel: extract structure from Rust function definition
        try (var registry = Helpers.createRegistry()) {
            org.junit.jupiter.api.Assumptions.assumeTrue(registry.hasLanguage("rust"), "Language 'rust' not available");
        }
        try (var registry = Helpers.createRegistry()) {
            String resultJson = registry.process("fn add(a: i32, b: i32) -> i32 {\n    a + b\n}\n", "rust");
            JsonObject intel = GSON.fromJson(resultJson, JsonObject.class);
            assertEquals("rust", intel.get("language").getAsString());
            assertTrue(intel.getAsJsonArray("structure").size() >= 1, "Should have at least 1 structure(s)");
            boolean foundKind = false;
            for (var elem : intel.getAsJsonArray("structure")) {
                if (elem.getAsJsonObject().get("kind").getAsString().equals("function")) {
                    foundKind = true;
                    break;
                }
            }
            assertTrue(foundKind, "Structure should contain a 'function' kind node");
            JsonObject metrics = intel.getAsJsonObject("metrics");
            assertTrue(metrics.get("total_lines").getAsInt() >= 3, "Should have at least 3 total line(s)");
            JsonObject metricsObj = intel.getAsJsonObject("metrics");
            assertEquals(0, metricsObj.get("error_count").getAsInt(), "Expected error_count 0");
        }
    }

}
