// Code generated by e2e-generator. DO NOT EDIT.
#![allow(clippy::too_many_lines)]

#[test]
fn registry_has_language_false() {
    // has_language('nonexistent') should return false
    assert_eq!(ts_pack_core::has_language("nonexistent"), false);
}

#[test]
fn registry_has_language_true() {
    // has_language('python') should return true
    assert_eq!(ts_pack_core::has_language("python"), true);
}

#[test]
fn registry_list_languages() {
    // available_languages should return a non-empty list
    let langs = ts_pack_core::available_languages();
    assert!(!langs.is_empty(), "available_languages() should not be empty");
}
