// Code generated by e2e-generator. DO NOT EDIT.
#![allow(clippy::too_many_lines)]

#[test]
fn smoke_c() {
    // Smoke test: load c and parse a simple snippet
    let mut parser = ts_pack_core::get_parser("c").expect("Failed to get parser for 'c'");
    let tree = parser.parse("int main() { return 0; }", None);
    assert!(tree.is_some(), "Parse tree should not be None");
    let tree = tree.unwrap();
    let root = tree.root_node();
    assert!(root.child_count() >= 1, "Root should have at least 1 child(ren), got {}", root.child_count());
}

#[test]
fn smoke_cpp() {
    // Smoke test: load cpp and parse a simple snippet
    let mut parser = ts_pack_core::get_parser("cpp").expect("Failed to get parser for 'cpp'");
    let tree = parser.parse("int main() { return 0; }", None);
    assert!(tree.is_some(), "Parse tree should not be None");
    let tree = tree.unwrap();
    let root = tree.root_node();
    assert!(root.child_count() >= 1, "Root should have at least 1 child(ren), got {}", root.child_count());
}

#[test]
fn smoke_go() {
    // Smoke test: load go and parse a simple snippet
    let mut parser = ts_pack_core::get_parser("go").expect("Failed to get parser for 'go'");
    let tree = parser.parse("package main", None);
    assert!(tree.is_some(), "Parse tree should not be None");
    let tree = tree.unwrap();
    let root = tree.root_node();
    assert!(root.child_count() >= 1, "Root should have at least 1 child(ren), got {}", root.child_count());
}

#[test]
fn smoke_html() {
    // Smoke test: load html and parse a simple snippet
    let mut parser = ts_pack_core::get_parser("html").expect("Failed to get parser for 'html'");
    let tree = parser.parse("<p>hello</p>", None);
    assert!(tree.is_some(), "Parse tree should not be None");
    let tree = tree.unwrap();
    let root = tree.root_node();
    assert!(root.child_count() >= 1, "Root should have at least 1 child(ren), got {}", root.child_count());
}

#[test]
fn smoke_java() {
    // Smoke test: load java and parse a simple snippet
    let mut parser = ts_pack_core::get_parser("java").expect("Failed to get parser for 'java'");
    let tree = parser.parse("class Main { public static void main(String[] args) {} }", None);
    assert!(tree.is_some(), "Parse tree should not be None");
    let tree = tree.unwrap();
    let root = tree.root_node();
    assert!(root.child_count() >= 1, "Root should have at least 1 child(ren), got {}", root.child_count());
}

#[test]
fn smoke_javascript() {
    // Smoke test: load javascript and parse a simple snippet
    let mut parser = ts_pack_core::get_parser("javascript").expect("Failed to get parser for 'javascript'");
    let tree = parser.parse("console.log('hello');", None);
    assert!(tree.is_some(), "Parse tree should not be None");
    let tree = tree.unwrap();
    let root = tree.root_node();
    assert!(root.child_count() >= 1, "Root should have at least 1 child(ren), got {}", root.child_count());
}

#[test]
fn smoke_python() {
    // Smoke test: load python and parse a simple snippet
    let mut parser = ts_pack_core::get_parser("python").expect("Failed to get parser for 'python'");
    let tree = parser.parse("print('hello')", None);
    assert!(tree.is_some(), "Parse tree should not be None");
    let tree = tree.unwrap();
    let root = tree.root_node();
    assert!(root.child_count() >= 1, "Root should have at least 1 child(ren), got {}", root.child_count());
}

#[test]
fn smoke_ruby() {
    // Smoke test: load ruby and parse a simple snippet
    let mut parser = ts_pack_core::get_parser("ruby").expect("Failed to get parser for 'ruby'");
    let tree = parser.parse("puts 'hello'", None);
    assert!(tree.is_some(), "Parse tree should not be None");
    let tree = tree.unwrap();
    let root = tree.root_node();
    assert!(root.child_count() >= 1, "Root should have at least 1 child(ren), got {}", root.child_count());
}

#[test]
fn smoke_rust() {
    // Smoke test: load rust and parse a simple snippet
    let mut parser = ts_pack_core::get_parser("rust").expect("Failed to get parser for 'rust'");
    let tree = parser.parse("fn main() {}", None);
    assert!(tree.is_some(), "Parse tree should not be None");
    let tree = tree.unwrap();
    let root = tree.root_node();
    assert!(root.child_count() >= 1, "Root should have at least 1 child(ren), got {}", root.child_count());
}

#[test]
fn smoke_typescript() {
    // Smoke test: load typescript and parse a simple snippet
    let mut parser = ts_pack_core::get_parser("typescript").expect("Failed to get parser for 'typescript'");
    let tree = parser.parse("const x: number = 42;", None);
    assert!(tree.is_some(), "Parse tree should not be None");
    let tree = tree.unwrap();
    let root = tree.root_node();
    assert!(root.child_count() >= 1, "Root should have at least 1 child(ren), got {}", root.child_count());
}
