// Code generated by e2e-generator. DO NOT EDIT.
#![allow(clippy::too_many_lines)]

#[test]
fn python_chunking_intel() {
    if !ts_pack_core::has_language("python") {
        eprintln!("Skipping: language 'python' not available");
        return;
    }
    // Intel: chunk multi-function Python source into multiple pieces
    let registry = ts_pack_core::LanguageRegistry::new();
    let (intel, chunks) = registry.process_and_chunk("def alpha():\n    pass\n\ndef beta():\n    pass\n\ndef gamma():\n    pass\n\ndef delta():\n    pass\n", "python", 30).expect("process_and_chunk failed");
    assert!(chunks.len() >= 2, "Expected at least 2 chunk(s), got {}", chunks.len());
    assert_eq!(intel.language, "python", "intel.language mismatch");
    assert!(intel.metrics.total_lines >= 8, "Expected at least 8 total line(s), got {}", intel.metrics.total_lines);
}

#[test]
fn python_function_intel() {
    if !ts_pack_core::has_language("python") {
        eprintln!("Skipping: language 'python' not available");
        return;
    }
    // Intel: extract structure from Python function definition
    let registry = ts_pack_core::LanguageRegistry::new();
    let intel = registry.process("def greet(name):\n    return f'Hello, {name}!'\n", "python").expect("process failed");
    assert_eq!(intel.language, "python", "intel.language mismatch");
    assert!(intel.structure.len() >= 1, "Expected at least 1 structure item(s), got {}", intel.structure.len());
    assert!(intel.structure.iter().any(|s| s.kind == ts_pack_core::StructureKind::Function), "Structure should contain a 'function' item");
    assert!(intel.metrics.total_lines >= 2, "Expected at least 2 total line(s), got {}", intel.metrics.total_lines);
    assert_eq!(intel.metrics.error_count, 0, "Expected error_count == 0, got {}", intel.metrics.error_count);
}

#[test]
fn rust_function_intel() {
    if !ts_pack_core::has_language("rust") {
        eprintln!("Skipping: language 'rust' not available");
        return;
    }
    // Intel: extract structure from Rust function definition
    let registry = ts_pack_core::LanguageRegistry::new();
    let intel = registry.process("fn add(a: i32, b: i32) -> i32 {\n    a + b\n}\n", "rust").expect("process failed");
    assert_eq!(intel.language, "rust", "intel.language mismatch");
    assert!(intel.structure.len() >= 1, "Expected at least 1 structure item(s), got {}", intel.structure.len());
    assert!(intel.structure.iter().any(|s| s.kind == ts_pack_core::StructureKind::Function), "Structure should contain a 'function' item");
    assert!(intel.metrics.total_lines >= 3, "Expected at least 3 total line(s), got {}", intel.metrics.total_lines);
    assert_eq!(intel.metrics.error_count, 0, "Expected error_count == 0, got {}", intel.metrics.error_count);
}
