// Code generated by e2e-generator. DO NOT EDIT.
#![allow(clippy::too_many_lines)]

#[test]
fn parsing_go_function() {
    if !ts_pack_core::has_language("go") {
        eprintln!("Skipping: language 'go' not available");
        return;
    }
    // Parse a Go function declaration and assert node type
    let mut parser = ts_pack_core::get_parser("go").expect("Failed to get parser for 'go'");
    let tree = parser.parse("package main\nfunc main() {}", None);
    assert!(tree.is_some(), "Parse tree should not be None");
    let tree = tree.unwrap();
    let root = tree.root_node();
    assert!(
        e2e_tests::tree_contains_node_type(root, "function_declaration"),
        "Tree should contain a 'function_declaration' node"
    );
}

#[test]
fn parsing_html_element() {
    if !ts_pack_core::has_language("html") {
        eprintln!("Skipping: language 'html' not available");
        return;
    }
    // Parse an HTML element and assert node type
    let mut parser = ts_pack_core::get_parser("html").expect("Failed to get parser for 'html'");
    let tree = parser.parse("<div>hello</div>", None);
    assert!(tree.is_some(), "Parse tree should not be None");
    let tree = tree.unwrap();
    let root = tree.root_node();
    assert!(
        e2e_tests::tree_contains_node_type(root, "element"),
        "Tree should contain a 'element' node"
    );
}

#[test]
fn parsing_javascript_class() {
    if !ts_pack_core::has_language("javascript") {
        eprintln!("Skipping: language 'javascript' not available");
        return;
    }
    // Parse a JavaScript class declaration.
    let mut parser = ts_pack_core::get_parser("javascript").expect("Failed to get parser for 'javascript'");
    let tree = parser.parse("class Foo { bar() {} }", None);
    assert!(tree.is_some(), "Parse tree should not be None");
    let tree = tree.unwrap();
    let root = tree.root_node();
    assert!(
        root.child_count() >= 1,
        "Root should have at least 1 child(ren), got {}",
        root.child_count()
    );
    assert!(
        e2e_tests::tree_contains_node_type(root, "class_declaration"),
        "Tree should contain a 'class_declaration' node"
    );
}

#[test]
fn parsing_javascript_variable() {
    if !ts_pack_core::has_language("javascript") {
        eprintln!("Skipping: language 'javascript' not available");
        return;
    }
    // Parse a JavaScript variable declaration and assert node type
    let mut parser = ts_pack_core::get_parser("javascript").expect("Failed to get parser for 'javascript'");
    let tree = parser.parse("const x = 1;", None);
    assert!(tree.is_some(), "Parse tree should not be None");
    let tree = tree.unwrap();
    let root = tree.root_node();
    assert!(
        e2e_tests::tree_contains_node_type(root, "lexical_declaration"),
        "Tree should contain a 'lexical_declaration' node"
    );
}

#[test]
fn parsing_python_function() {
    if !ts_pack_core::has_language("python") {
        eprintln!("Skipping: language 'python' not available");
        return;
    }
    // Parse a Python function definition and assert node type
    let mut parser = ts_pack_core::get_parser("python").expect("Failed to get parser for 'python'");
    let tree = parser.parse("def hello(): pass", None);
    assert!(tree.is_some(), "Parse tree should not be None");
    let tree = tree.unwrap();
    let root = tree.root_node();
    assert!(
        e2e_tests::tree_contains_node_type(root, "function_definition"),
        "Tree should contain a 'function_definition' node"
    );
}

#[test]
fn parsing_rust_function() {
    if !ts_pack_core::has_language("rust") {
        eprintln!("Skipping: language 'rust' not available");
        return;
    }
    // Parse a Rust function definition and assert node type
    let mut parser = ts_pack_core::get_parser("rust").expect("Failed to get parser for 'rust'");
    let tree = parser.parse("fn main() {}", None);
    assert!(tree.is_some(), "Parse tree should not be None");
    let tree = tree.unwrap();
    let root = tree.root_node();
    assert!(
        e2e_tests::tree_contains_node_type(root, "function_item"),
        "Tree should contain a 'function_item' node"
    );
}

#[test]
fn parsing_rust_struct() {
    if !ts_pack_core::has_language("rust") {
        eprintln!("Skipping: language 'rust' not available");
        return;
    }
    // Parse a Rust struct definition.
    let mut parser = ts_pack_core::get_parser("rust").expect("Failed to get parser for 'rust'");
    let tree = parser.parse("struct Point { x: f64, y: f64 }", None);
    assert!(tree.is_some(), "Parse tree should not be None");
    let tree = tree.unwrap();
    let root = tree.root_node();
    assert!(
        root.child_count() >= 1,
        "Root should have at least 1 child(ren), got {}",
        root.child_count()
    );
}
