// Code generated by e2e-generator. DO NOT EDIT.

import { process, processAndChunk } from "@kreuzberg/tree-sitter-language-pack";

/**
 * Placeholder type for tree-sitter node objects returned from native parsing.
 */
export interface TreeNode {
  type: string;
  childCount: number;
  children: TreeNode[];
  isMissing: boolean;
}

/**
 * Check whether a tree-sitter node or any descendant has the given type.
 */
export function treeContainsNodeType(node: TreeNode, nodeType: string): boolean {
  if (node.type === nodeType) {
    return true;
  }
  for (const child of node.children) {
    if (treeContainsNodeType(child, nodeType)) {
      return true;
    }
  }
  return false;
}

/**
 * Check whether a tree-sitter node or any descendant is an ERROR node.
 */
export function treeHasErrorNodes(node: TreeNode): boolean {
  if (node.type === "ERROR" || node.isMissing) {
    return true;
  }
  for (const child of node.children) {
    if (treeHasErrorNodes(child)) {
      return true;
    }
  }
  return false;
}

/**
 * Re-export process and processAndChunk for test use.
 */
export { process, processAndChunk };
