// Code generated by e2e-generator. DO NOT EDIT.

import { describe, it, expect } from "vitest";
import { availableLanguages, hasLanguage, getLanguagePtr, process, processAndChunk } from "./helpers";

describe("intel", () => {
  it("python_chunking_intel", () => {
    // Intel: chunk multi-function Python source into multiple pieces
    if (!hasLanguage("python")) {
      console.log("Skipping: language 'python' not available");
      return;
    }
    const resultJson = processAndChunk("def alpha():\n    pass\n\ndef beta():\n    pass\n\ndef gamma():\n    pass\n\ndef delta():\n    pass\n", "python", 2);
    const result = JSON.parse(resultJson);
    const intel = result.intelligence;
    const chunks = result.chunks;
    expect(intel.language).toBe("python");
    expect((intel.metrics || {}).total_lines || 0).toBeGreaterThanOrEqual(8);
    expect((chunks || []).length).toBeGreaterThanOrEqual(2);
  });

  it("python_function_intel", () => {
    // Intel: extract structure from Python function definition
    if (!hasLanguage("python")) {
      console.log("Skipping: language 'python' not available");
      return;
    }
    const resultJson = process("def greet(name):\n    return f'Hello, {name}!'\n", "python");
    const result = JSON.parse(resultJson);
    const intel = result;
    expect(intel.language).toBe("python");
    expect((intel.structure || []).length).toBeGreaterThanOrEqual(1);
    expect((intel.structure || []).some((s: any) => s.kind === "function")).toBe(true);
    expect((intel.metrics || {}).total_lines || 0).toBeGreaterThanOrEqual(2);
    expect((intel.metrics || {}).error_count || 0).toBe(0);
  });

  it("rust_function_intel", () => {
    // Intel: extract structure from Rust function definition
    if (!hasLanguage("rust")) {
      console.log("Skipping: language 'rust' not available");
      return;
    }
    const resultJson = process("fn add(a: i32, b: i32) -> i32 {\n    a + b\n}\n", "rust");
    const result = JSON.parse(resultJson);
    const intel = result;
    expect(intel.language).toBe("rust");
    expect((intel.structure || []).length).toBeGreaterThanOrEqual(1);
    expect((intel.structure || []).some((s: any) => s.kind === "function")).toBe(true);
    expect((intel.metrics || {}).total_lines || 0).toBeGreaterThanOrEqual(3);
    expect((intel.metrics || {}).error_count || 0).toBe(0);
  });

});
