// Code generated by e2e-generator. DO NOT EDIT.

import { describe, it, expect } from "vitest";
import { availableLanguages, hasLanguage, getLanguagePtr, process, processAndChunk } from "./helpers";

describe("parsing", () => {
  it("parsing_go_function", () => {
    // Parse a Go function declaration and assert node type
    if (!hasLanguage("go")) {
      console.log("Skipping: language 'go' not available");
      return;
    }
    const ptr = getLanguagePtr("go");
    expect(ptr).toBeTruthy();
  });

  it("parsing_html_element", () => {
    // Parse an HTML element and assert node type
    if (!hasLanguage("html")) {
      console.log("Skipping: language 'html' not available");
      return;
    }
    const ptr = getLanguagePtr("html");
    expect(ptr).toBeTruthy();
  });

  it("parsing_javascript_class", () => {
    // Parse a JavaScript class declaration.
    if (!hasLanguage("javascript")) {
      console.log("Skipping: language 'javascript' not available");
      return;
    }
    const ptr = getLanguagePtr("javascript");
    expect(ptr).toBeTruthy();
  });

  it("parsing_javascript_variable", () => {
    // Parse a JavaScript variable declaration and assert node type
    if (!hasLanguage("javascript")) {
      console.log("Skipping: language 'javascript' not available");
      return;
    }
    const ptr = getLanguagePtr("javascript");
    expect(ptr).toBeTruthy();
  });

  it("parsing_python_function", () => {
    // Parse a Python function definition and assert node type
    if (!hasLanguage("python")) {
      console.log("Skipping: language 'python' not available");
      return;
    }
    const ptr = getLanguagePtr("python");
    expect(ptr).toBeTruthy();
  });

  it("parsing_rust_function", () => {
    // Parse a Rust function definition and assert node type
    if (!hasLanguage("rust")) {
      console.log("Skipping: language 'rust' not available");
      return;
    }
    const ptr = getLanguagePtr("rust");
    expect(ptr).toBeTruthy();
  });

  it("parsing_rust_struct", () => {
    // Parse a Rust struct definition.
    if (!hasLanguage("rust")) {
      console.log("Skipping: language 'rust' not available");
      return;
    }
    const ptr = getLanguagePtr("rust");
    expect(ptr).toBeTruthy();
  });

});
