// Code generated by e2e-generator. DO NOT EDIT.

import { describe, it, expect } from "vitest";
import { availableLanguages, hasLanguage, getLanguagePtr, process, processAndChunk } from "./helpers";

describe("smoke", () => {
  it("smoke_actionscript", () => {
    // Smoke test: load actionscript and parse a simple snippet
    const ptr = getLanguagePtr("actionscript");
    expect(ptr).toBeTruthy();
  });

  it("smoke_ada", () => {
    // Smoke test: load ada and parse a simple snippet
    const ptr = getLanguagePtr("ada");
    expect(ptr).toBeTruthy();
  });

  it("smoke_agda", () => {
    // Smoke test: load agda and parse a simple snippet
    const ptr = getLanguagePtr("agda");
    expect(ptr).toBeTruthy();
  });

  it("smoke_apex", () => {
    // Smoke test: load apex and parse a simple snippet
    const ptr = getLanguagePtr("apex");
    expect(ptr).toBeTruthy();
  });

  it("smoke_arduino", () => {
    // Smoke test: load arduino and parse a simple snippet
    const ptr = getLanguagePtr("arduino");
    expect(ptr).toBeTruthy();
  });

  it("smoke_asm", () => {
    // Smoke test: load asm and parse a simple snippet
    const ptr = getLanguagePtr("asm");
    expect(ptr).toBeTruthy();
  });

  it("smoke_astro", () => {
    // Smoke test: load astro and parse a simple snippet
    const ptr = getLanguagePtr("astro");
    expect(ptr).toBeTruthy();
  });

  it("smoke_bash", () => {
    // Smoke test: load bash and parse a simple snippet
    const ptr = getLanguagePtr("bash");
    expect(ptr).toBeTruthy();
  });

  it("smoke_beancount", () => {
    // Smoke test: load beancount and parse a simple snippet
    const ptr = getLanguagePtr("beancount");
    expect(ptr).toBeTruthy();
  });

  it("smoke_bibtex", () => {
    // Smoke test: load bibtex and parse a simple snippet
    const ptr = getLanguagePtr("bibtex");
    expect(ptr).toBeTruthy();
  });

  it("smoke_bicep", () => {
    // Smoke test: load bicep and parse a simple snippet
    const ptr = getLanguagePtr("bicep");
    expect(ptr).toBeTruthy();
  });

  it("smoke_bitbake", () => {
    // Smoke test: load bitbake and parse a simple snippet
    const ptr = getLanguagePtr("bitbake");
    expect(ptr).toBeTruthy();
  });

  it("smoke_bsl", () => {
    // Smoke test: load bsl and parse a simple snippet
    const ptr = getLanguagePtr("bsl");
    expect(ptr).toBeTruthy();
  });

  it("smoke_c", () => {
    // Smoke test: load c and parse a simple snippet
    const ptr = getLanguagePtr("c");
    expect(ptr).toBeTruthy();
  });

  it("smoke_cairo", () => {
    // Smoke test: load cairo and parse a simple snippet
    const ptr = getLanguagePtr("cairo");
    expect(ptr).toBeTruthy();
  });

  it("smoke_capnp", () => {
    // Smoke test: load capnp and parse a simple snippet
    const ptr = getLanguagePtr("capnp");
    expect(ptr).toBeTruthy();
  });

  it("smoke_chatito", () => {
    // Smoke test: load chatito and parse a simple snippet
    const ptr = getLanguagePtr("chatito");
    expect(ptr).toBeTruthy();
  });

  it("smoke_clarity", () => {
    // Smoke test: load clarity and parse a simple snippet
    const ptr = getLanguagePtr("clarity");
    expect(ptr).toBeTruthy();
  });

  it("smoke_clojure", () => {
    // Smoke test: load clojure and parse a simple snippet
    const ptr = getLanguagePtr("clojure");
    expect(ptr).toBeTruthy();
  });

  it("smoke_cmake", () => {
    // Smoke test: load cmake and parse a simple snippet
    const ptr = getLanguagePtr("cmake");
    expect(ptr).toBeTruthy();
  });

  it("smoke_cobol", () => {
    // Smoke test: load cobol and parse a simple snippet
    const ptr = getLanguagePtr("cobol");
    expect(ptr).toBeTruthy();
  });

  it("smoke_comment", () => {
    // Smoke test: load comment and parse a simple snippet
    const ptr = getLanguagePtr("comment");
    expect(ptr).toBeTruthy();
  });

  it("smoke_commonlisp", () => {
    // Smoke test: load commonlisp and parse a simple snippet
    const ptr = getLanguagePtr("commonlisp");
    expect(ptr).toBeTruthy();
  });

  it("smoke_cpon", () => {
    // Smoke test: load cpon and parse a simple snippet
    const ptr = getLanguagePtr("cpon");
    expect(ptr).toBeTruthy();
  });

  it("smoke_cpp", () => {
    // Smoke test: load cpp and parse a simple snippet
    const ptr = getLanguagePtr("cpp");
    expect(ptr).toBeTruthy();
  });

  it("smoke_css", () => {
    // Smoke test: load css and parse a simple snippet
    const ptr = getLanguagePtr("css");
    expect(ptr).toBeTruthy();
  });

  it("smoke_csv", () => {
    // Smoke test: load csv and parse a simple snippet
    const ptr = getLanguagePtr("csv");
    expect(ptr).toBeTruthy();
  });

  it("smoke_cuda", () => {
    // Smoke test: load cuda and parse a simple snippet
    const ptr = getLanguagePtr("cuda");
    expect(ptr).toBeTruthy();
  });

  it("smoke_d", () => {
    // Smoke test: load d and parse a simple snippet
    const ptr = getLanguagePtr("d");
    expect(ptr).toBeTruthy();
  });

  it("smoke_dart", () => {
    // Smoke test: load dart and parse a simple snippet
    const ptr = getLanguagePtr("dart");
    expect(ptr).toBeTruthy();
  });

  it("smoke_dockerfile", () => {
    // Smoke test: load dockerfile and parse a simple snippet
    const ptr = getLanguagePtr("dockerfile");
    expect(ptr).toBeTruthy();
  });

  it("smoke_doxygen", () => {
    // Smoke test: load doxygen and parse a simple snippet
    const ptr = getLanguagePtr("doxygen");
    expect(ptr).toBeTruthy();
  });

  it("smoke_dtd", () => {
    // Smoke test: load dtd and parse a simple snippet
    const ptr = getLanguagePtr("dtd");
    expect(ptr).toBeTruthy();
  });

  it("smoke_elisp", () => {
    // Smoke test: load elisp and parse a simple snippet
    const ptr = getLanguagePtr("elisp");
    expect(ptr).toBeTruthy();
  });

  it("smoke_elixir", () => {
    // Smoke test: load elixir and parse a simple snippet
    const ptr = getLanguagePtr("elixir");
    expect(ptr).toBeTruthy();
  });

  it("smoke_elm", () => {
    // Smoke test: load elm and parse a simple snippet
    const ptr = getLanguagePtr("elm");
    expect(ptr).toBeTruthy();
  });

  it("smoke_erlang", () => {
    // Smoke test: load erlang and parse a simple snippet
    const ptr = getLanguagePtr("erlang");
    expect(ptr).toBeTruthy();
  });

  it("smoke_fennel", () => {
    // Smoke test: load fennel and parse a simple snippet
    const ptr = getLanguagePtr("fennel");
    expect(ptr).toBeTruthy();
  });

  it("smoke_firrtl", () => {
    // Smoke test: load firrtl and parse a simple snippet
    const ptr = getLanguagePtr("firrtl");
    expect(ptr).toBeTruthy();
  });

  it("smoke_fish", () => {
    // Smoke test: load fish and parse a simple snippet
    const ptr = getLanguagePtr("fish");
    expect(ptr).toBeTruthy();
  });

  it("smoke_fortran", () => {
    // Smoke test: load fortran and parse a simple snippet
    const ptr = getLanguagePtr("fortran");
    expect(ptr).toBeTruthy();
  });

  it("smoke_fsharp", () => {
    // Smoke test: load fsharp and parse a simple snippet
    const ptr = getLanguagePtr("fsharp");
    expect(ptr).toBeTruthy();
  });

  it("smoke_fsharp_signature", () => {
    // Smoke test: load fsharp_signature and parse a simple snippet
    const ptr = getLanguagePtr("fsharp_signature");
    expect(ptr).toBeTruthy();
  });

  it("smoke_func", () => {
    // Smoke test: load func and parse a simple snippet
    const ptr = getLanguagePtr("func");
    expect(ptr).toBeTruthy();
  });

  it("smoke_gdscript", () => {
    // Smoke test: load gdscript and parse a simple snippet
    const ptr = getLanguagePtr("gdscript");
    expect(ptr).toBeTruthy();
  });

  it("smoke_gitattributes", () => {
    // Smoke test: load gitattributes and parse a simple snippet
    const ptr = getLanguagePtr("gitattributes");
    expect(ptr).toBeTruthy();
  });

  it("smoke_gitcommit", () => {
    // Smoke test: load gitcommit and parse a simple snippet
    const ptr = getLanguagePtr("gitcommit");
    expect(ptr).toBeTruthy();
  });

  it("smoke_gitignore", () => {
    // Smoke test: load gitignore and parse a simple snippet
    const ptr = getLanguagePtr("gitignore");
    expect(ptr).toBeTruthy();
  });

  it("smoke_gleam", () => {
    // Smoke test: load gleam and parse a simple snippet
    const ptr = getLanguagePtr("gleam");
    expect(ptr).toBeTruthy();
  });

  it("smoke_glsl", () => {
    // Smoke test: load glsl and parse a simple snippet
    const ptr = getLanguagePtr("glsl");
    expect(ptr).toBeTruthy();
  });

  it("smoke_gn", () => {
    // Smoke test: load gn and parse a simple snippet
    const ptr = getLanguagePtr("gn");
    expect(ptr).toBeTruthy();
  });

  it("smoke_go", () => {
    // Smoke test: load go and parse a simple snippet
    const ptr = getLanguagePtr("go");
    expect(ptr).toBeTruthy();
  });

  it("smoke_gomod", () => {
    // Smoke test: load gomod and parse a simple snippet
    const ptr = getLanguagePtr("gomod");
    expect(ptr).toBeTruthy();
  });

  it("smoke_gosum", () => {
    // Smoke test: load gosum and parse a simple snippet
    const ptr = getLanguagePtr("gosum");
    expect(ptr).toBeTruthy();
  });

  it("smoke_graphql", () => {
    // Smoke test: load graphql and parse a simple snippet
    const ptr = getLanguagePtr("graphql");
    expect(ptr).toBeTruthy();
  });

  it("smoke_groovy", () => {
    // Smoke test: load groovy and parse a simple snippet
    const ptr = getLanguagePtr("groovy");
    expect(ptr).toBeTruthy();
  });

  it("smoke_gstlaunch", () => {
    // Smoke test: load gstlaunch and parse a simple snippet
    const ptr = getLanguagePtr("gstlaunch");
    expect(ptr).toBeTruthy();
  });

  it("smoke_hack", () => {
    // Smoke test: load hack and parse a simple snippet
    const ptr = getLanguagePtr("hack");
    expect(ptr).toBeTruthy();
  });

  it("smoke_hare", () => {
    // Smoke test: load hare and parse a simple snippet
    const ptr = getLanguagePtr("hare");
    expect(ptr).toBeTruthy();
  });

  it("smoke_haskell", () => {
    // Smoke test: load haskell and parse a simple snippet
    const ptr = getLanguagePtr("haskell");
    expect(ptr).toBeTruthy();
  });

  it("smoke_haxe", () => {
    // Smoke test: load haxe and parse a simple snippet
    const ptr = getLanguagePtr("haxe");
    expect(ptr).toBeTruthy();
  });

  it("smoke_hcl", () => {
    // Smoke test: load hcl and parse a simple snippet
    const ptr = getLanguagePtr("hcl");
    expect(ptr).toBeTruthy();
  });

  it("smoke_heex", () => {
    // Smoke test: load heex and parse a simple snippet
    const ptr = getLanguagePtr("heex");
    expect(ptr).toBeTruthy();
  });

  it("smoke_hlsl", () => {
    // Smoke test: load hlsl and parse a simple snippet
    const ptr = getLanguagePtr("hlsl");
    expect(ptr).toBeTruthy();
  });

  it("smoke_html", () => {
    // Smoke test: load html and parse a simple snippet
    const ptr = getLanguagePtr("html");
    expect(ptr).toBeTruthy();
  });

  it("smoke_hyprlang", () => {
    // Smoke test: load hyprlang and parse a simple snippet
    const ptr = getLanguagePtr("hyprlang");
    expect(ptr).toBeTruthy();
  });

  it("smoke_ini", () => {
    // Smoke test: load ini and parse a simple snippet
    const ptr = getLanguagePtr("ini");
    expect(ptr).toBeTruthy();
  });

  it("smoke_ispc", () => {
    // Smoke test: load ispc and parse a simple snippet
    const ptr = getLanguagePtr("ispc");
    expect(ptr).toBeTruthy();
  });

  it("smoke_janet", () => {
    // Smoke test: load janet and parse a simple snippet
    const ptr = getLanguagePtr("janet");
    expect(ptr).toBeTruthy();
  });

  it("smoke_java", () => {
    // Smoke test: load java and parse a simple snippet
    const ptr = getLanguagePtr("java");
    expect(ptr).toBeTruthy();
  });

  it("smoke_javascript", () => {
    // Smoke test: load javascript and parse a simple snippet
    const ptr = getLanguagePtr("javascript");
    expect(ptr).toBeTruthy();
  });

  it("smoke_jsdoc", () => {
    // Smoke test: load jsdoc and parse a simple snippet
    const ptr = getLanguagePtr("jsdoc");
    expect(ptr).toBeTruthy();
  });

  it("smoke_json", () => {
    // Smoke test: load json and parse a simple snippet
    const ptr = getLanguagePtr("json");
    expect(ptr).toBeTruthy();
  });

  it("smoke_jsonnet", () => {
    // Smoke test: load jsonnet and parse a simple snippet
    const ptr = getLanguagePtr("jsonnet");
    expect(ptr).toBeTruthy();
  });

  it("smoke_julia", () => {
    // Smoke test: load julia and parse a simple snippet
    const ptr = getLanguagePtr("julia");
    expect(ptr).toBeTruthy();
  });

  it("smoke_kconfig", () => {
    // Smoke test: load kconfig and parse a simple snippet
    const ptr = getLanguagePtr("kconfig");
    expect(ptr).toBeTruthy();
  });

  it("smoke_kdl", () => {
    // Smoke test: load kdl and parse a simple snippet
    const ptr = getLanguagePtr("kdl");
    expect(ptr).toBeTruthy();
  });

  it("smoke_kotlin", () => {
    // Smoke test: load kotlin and parse a simple snippet
    const ptr = getLanguagePtr("kotlin");
    expect(ptr).toBeTruthy();
  });

  it("smoke_latex", () => {
    // Smoke test: load latex and parse a simple snippet
    const ptr = getLanguagePtr("latex");
    expect(ptr).toBeTruthy();
  });

  it("smoke_linkerscript", () => {
    // Smoke test: load linkerscript and parse a simple snippet
    const ptr = getLanguagePtr("linkerscript");
    expect(ptr).toBeTruthy();
  });

  it("smoke_llvm", () => {
    // Smoke test: load llvm and parse a simple snippet
    const ptr = getLanguagePtr("llvm");
    expect(ptr).toBeTruthy();
  });

  it("smoke_lua", () => {
    // Smoke test: load lua and parse a simple snippet
    const ptr = getLanguagePtr("lua");
    expect(ptr).toBeTruthy();
  });

  it("smoke_luadoc", () => {
    // Smoke test: load luadoc and parse a simple snippet
    const ptr = getLanguagePtr("luadoc");
    expect(ptr).toBeTruthy();
  });

  it("smoke_luap", () => {
    // Smoke test: load luap and parse a simple snippet
    const ptr = getLanguagePtr("luap");
    expect(ptr).toBeTruthy();
  });

  it("smoke_luau", () => {
    // Smoke test: load luau and parse a simple snippet
    const ptr = getLanguagePtr("luau");
    expect(ptr).toBeTruthy();
  });

  it("smoke_magik", () => {
    // Smoke test: load magik and parse a simple snippet
    const ptr = getLanguagePtr("magik");
    expect(ptr).toBeTruthy();
  });

  it("smoke_make", () => {
    // Smoke test: load make and parse a simple snippet
    const ptr = getLanguagePtr("make");
    expect(ptr).toBeTruthy();
  });

  it("smoke_markdown", () => {
    // Smoke test: load markdown and parse a simple snippet
    const ptr = getLanguagePtr("markdown");
    expect(ptr).toBeTruthy();
  });

  it("smoke_markdown_inline", () => {
    // Smoke test: load markdown_inline and parse a simple snippet
    const ptr = getLanguagePtr("markdown_inline");
    expect(ptr).toBeTruthy();
  });

  it("smoke_matlab", () => {
    // Smoke test: load matlab and parse a simple snippet
    const ptr = getLanguagePtr("matlab");
    expect(ptr).toBeTruthy();
  });

  it("smoke_mermaid", () => {
    // Smoke test: load mermaid and parse a simple snippet
    const ptr = getLanguagePtr("mermaid");
    expect(ptr).toBeTruthy();
  });

  it("smoke_meson", () => {
    // Smoke test: load meson and parse a simple snippet
    const ptr = getLanguagePtr("meson");
    expect(ptr).toBeTruthy();
  });

  it("smoke_netlinx", () => {
    // Smoke test: load netlinx and parse a simple snippet
    const ptr = getLanguagePtr("netlinx");
    expect(ptr).toBeTruthy();
  });

  it("smoke_nim", () => {
    // Smoke test: load nim and parse a simple snippet
    const ptr = getLanguagePtr("nim");
    expect(ptr).toBeTruthy();
  });

  it("smoke_ninja", () => {
    // Smoke test: load ninja and parse a simple snippet
    const ptr = getLanguagePtr("ninja");
    expect(ptr).toBeTruthy();
  });

  it("smoke_nix", () => {
    // Smoke test: load nix and parse a simple snippet
    const ptr = getLanguagePtr("nix");
    expect(ptr).toBeTruthy();
  });

  it("smoke_nqc", () => {
    // Smoke test: load nqc and parse a simple snippet
    const ptr = getLanguagePtr("nqc");
    expect(ptr).toBeTruthy();
  });

  it("smoke_objc", () => {
    // Smoke test: load objc and parse a simple snippet
    const ptr = getLanguagePtr("objc");
    expect(ptr).toBeTruthy();
  });

  it("smoke_ocaml", () => {
    // Smoke test: load ocaml and parse a simple snippet
    const ptr = getLanguagePtr("ocaml");
    expect(ptr).toBeTruthy();
  });

  it("smoke_ocaml_interface", () => {
    // Smoke test: load ocaml_interface and parse a simple snippet
    const ptr = getLanguagePtr("ocaml_interface");
    expect(ptr).toBeTruthy();
  });

  it("smoke_odin", () => {
    // Smoke test: load odin and parse a simple snippet
    const ptr = getLanguagePtr("odin");
    expect(ptr).toBeTruthy();
  });

  it("smoke_org", () => {
    // Smoke test: load org and parse a simple snippet
    const ptr = getLanguagePtr("org");
    expect(ptr).toBeTruthy();
  });

  it("smoke_pascal", () => {
    // Smoke test: load pascal and parse a simple snippet
    const ptr = getLanguagePtr("pascal");
    expect(ptr).toBeTruthy();
  });

  it("smoke_pem", () => {
    // Smoke test: load pem and parse a simple snippet
    const ptr = getLanguagePtr("pem");
    expect(ptr).toBeTruthy();
  });

  it("smoke_perl", () => {
    // Smoke test: load perl and parse a simple snippet
    const ptr = getLanguagePtr("perl");
    expect(ptr).toBeTruthy();
  });

  it("smoke_pgn", () => {
    // Smoke test: load pgn and parse a simple snippet
    const ptr = getLanguagePtr("pgn");
    expect(ptr).toBeTruthy();
  });

  it("smoke_php", () => {
    // Smoke test: load php and parse a simple snippet
    const ptr = getLanguagePtr("php");
    expect(ptr).toBeTruthy();
  });

  it("smoke_po", () => {
    // Smoke test: load po and parse a simple snippet
    const ptr = getLanguagePtr("po");
    expect(ptr).toBeTruthy();
  });

  it("smoke_pony", () => {
    // Smoke test: load pony and parse a simple snippet
    const ptr = getLanguagePtr("pony");
    expect(ptr).toBeTruthy();
  });

  it("smoke_powershell", () => {
    // Smoke test: load powershell and parse a simple snippet
    const ptr = getLanguagePtr("powershell");
    expect(ptr).toBeTruthy();
  });

  it("smoke_printf", () => {
    // Smoke test: load printf and parse a simple snippet
    const ptr = getLanguagePtr("printf");
    expect(ptr).toBeTruthy();
  });

  it("smoke_prisma", () => {
    // Smoke test: load prisma and parse a simple snippet
    const ptr = getLanguagePtr("prisma");
    expect(ptr).toBeTruthy();
  });

  it("smoke_properties", () => {
    // Smoke test: load properties and parse a simple snippet
    const ptr = getLanguagePtr("properties");
    expect(ptr).toBeTruthy();
  });

  it("smoke_proto", () => {
    // Smoke test: load proto and parse a simple snippet
    const ptr = getLanguagePtr("proto");
    expect(ptr).toBeTruthy();
  });

  it("smoke_psv", () => {
    // Smoke test: load psv and parse a simple snippet
    const ptr = getLanguagePtr("psv");
    expect(ptr).toBeTruthy();
  });

  it("smoke_puppet", () => {
    // Smoke test: load puppet and parse a simple snippet
    const ptr = getLanguagePtr("puppet");
    expect(ptr).toBeTruthy();
  });

  it("smoke_purescript", () => {
    // Smoke test: load purescript and parse a simple snippet
    const ptr = getLanguagePtr("purescript");
    expect(ptr).toBeTruthy();
  });

  it("smoke_pymanifest", () => {
    // Smoke test: load pymanifest and parse a simple snippet
    const ptr = getLanguagePtr("pymanifest");
    expect(ptr).toBeTruthy();
  });

  it("smoke_python", () => {
    // Smoke test: load python and parse a simple snippet
    const ptr = getLanguagePtr("python");
    expect(ptr).toBeTruthy();
  });

  it("smoke_qmldir", () => {
    // Smoke test: load qmldir and parse a simple snippet
    const ptr = getLanguagePtr("qmldir");
    expect(ptr).toBeTruthy();
  });

  it("smoke_qmljs", () => {
    // Smoke test: load qmljs and parse a simple snippet
    const ptr = getLanguagePtr("qmljs");
    expect(ptr).toBeTruthy();
  });

  it("smoke_query", () => {
    // Smoke test: load query and parse a simple snippet
    const ptr = getLanguagePtr("query");
    expect(ptr).toBeTruthy();
  });

  it("smoke_r", () => {
    // Smoke test: load r and parse a simple snippet
    const ptr = getLanguagePtr("r");
    expect(ptr).toBeTruthy();
  });

  it("smoke_racket", () => {
    // Smoke test: load racket and parse a simple snippet
    const ptr = getLanguagePtr("racket");
    expect(ptr).toBeTruthy();
  });

  it("smoke_re2c", () => {
    // Smoke test: load re2c and parse a simple snippet
    const ptr = getLanguagePtr("re2c");
    expect(ptr).toBeTruthy();
  });

  it("smoke_readline", () => {
    // Smoke test: load readline and parse a simple snippet
    const ptr = getLanguagePtr("readline");
    expect(ptr).toBeTruthy();
  });

  it("smoke_rego", () => {
    // Smoke test: load rego and parse a simple snippet
    const ptr = getLanguagePtr("rego");
    expect(ptr).toBeTruthy();
  });

  it("smoke_requirements", () => {
    // Smoke test: load requirements and parse a simple snippet
    const ptr = getLanguagePtr("requirements");
    expect(ptr).toBeTruthy();
  });

  it("smoke_ron", () => {
    // Smoke test: load ron and parse a simple snippet
    const ptr = getLanguagePtr("ron");
    expect(ptr).toBeTruthy();
  });

  it("smoke_rst", () => {
    // Smoke test: load rst and parse a simple snippet
    const ptr = getLanguagePtr("rst");
    expect(ptr).toBeTruthy();
  });

  it("smoke_ruby", () => {
    // Smoke test: load ruby and parse a simple snippet
    const ptr = getLanguagePtr("ruby");
    expect(ptr).toBeTruthy();
  });

  it("smoke_rust", () => {
    // Smoke test: load rust and parse a simple snippet
    const ptr = getLanguagePtr("rust");
    expect(ptr).toBeTruthy();
  });

  it("smoke_scala", () => {
    // Smoke test: load scala and parse a simple snippet
    const ptr = getLanguagePtr("scala");
    expect(ptr).toBeTruthy();
  });

  it("smoke_scheme", () => {
    // Smoke test: load scheme and parse a simple snippet
    const ptr = getLanguagePtr("scheme");
    expect(ptr).toBeTruthy();
  });

  it("smoke_scss", () => {
    // Smoke test: load scss and parse a simple snippet
    const ptr = getLanguagePtr("scss");
    expect(ptr).toBeTruthy();
  });

  it("smoke_smali", () => {
    // Smoke test: load smali and parse a simple snippet
    const ptr = getLanguagePtr("smali");
    expect(ptr).toBeTruthy();
  });

  it("smoke_smithy", () => {
    // Smoke test: load smithy and parse a simple snippet
    const ptr = getLanguagePtr("smithy");
    expect(ptr).toBeTruthy();
  });

  it("smoke_solidity", () => {
    // Smoke test: load solidity and parse a simple snippet
    const ptr = getLanguagePtr("solidity");
    expect(ptr).toBeTruthy();
  });

  it("smoke_sparql", () => {
    // Smoke test: load sparql and parse a simple snippet
    const ptr = getLanguagePtr("sparql");
    expect(ptr).toBeTruthy();
  });

  it("smoke_sql", () => {
    // Smoke test: load sql and parse a simple snippet
    const ptr = getLanguagePtr("sql");
    expect(ptr).toBeTruthy();
  });

  it("smoke_squirrel", () => {
    // Smoke test: load squirrel and parse a simple snippet
    const ptr = getLanguagePtr("squirrel");
    expect(ptr).toBeTruthy();
  });

  it("smoke_starlark", () => {
    // Smoke test: load starlark and parse a simple snippet
    const ptr = getLanguagePtr("starlark");
    expect(ptr).toBeTruthy();
  });

  it("smoke_svelte", () => {
    // Smoke test: load svelte and parse a simple snippet
    const ptr = getLanguagePtr("svelte");
    expect(ptr).toBeTruthy();
  });

  it("smoke_swift", () => {
    // Smoke test: load swift and parse a simple snippet
    const ptr = getLanguagePtr("swift");
    expect(ptr).toBeTruthy();
  });

  it("smoke_tablegen", () => {
    // Smoke test: load tablegen and parse a simple snippet
    const ptr = getLanguagePtr("tablegen");
    expect(ptr).toBeTruthy();
  });

  it("smoke_tcl", () => {
    // Smoke test: load tcl and parse a simple snippet
    const ptr = getLanguagePtr("tcl");
    expect(ptr).toBeTruthy();
  });

  it("smoke_terraform", () => {
    // Smoke test: load terraform and parse a simple snippet
    const ptr = getLanguagePtr("terraform");
    expect(ptr).toBeTruthy();
  });

  it("smoke_test", () => {
    // Smoke test: load test and parse a simple snippet
    const ptr = getLanguagePtr("test");
    expect(ptr).toBeTruthy();
  });

  it("smoke_thrift", () => {
    // Smoke test: load thrift and parse a simple snippet
    const ptr = getLanguagePtr("thrift");
    expect(ptr).toBeTruthy();
  });

  it("smoke_toml", () => {
    // Smoke test: load toml and parse a simple snippet
    const ptr = getLanguagePtr("toml");
    expect(ptr).toBeTruthy();
  });

  it("smoke_tsv", () => {
    // Smoke test: load tsv and parse a simple snippet
    const ptr = getLanguagePtr("tsv");
    expect(ptr).toBeTruthy();
  });

  it("smoke_tsx", () => {
    // Smoke test: load tsx and parse a simple snippet
    const ptr = getLanguagePtr("tsx");
    expect(ptr).toBeTruthy();
  });

  it("smoke_twig", () => {
    // Smoke test: load twig and parse a simple snippet
    const ptr = getLanguagePtr("twig");
    expect(ptr).toBeTruthy();
  });

  it("smoke_typescript", () => {
    // Smoke test: load typescript and parse a simple snippet
    const ptr = getLanguagePtr("typescript");
    expect(ptr).toBeTruthy();
  });

  it("smoke_typst", () => {
    // Smoke test: load typst and parse a simple snippet
    const ptr = getLanguagePtr("typst");
    expect(ptr).toBeTruthy();
  });

  it("smoke_udev", () => {
    // Smoke test: load udev and parse a simple snippet
    const ptr = getLanguagePtr("udev");
    expect(ptr).toBeTruthy();
  });

  it("smoke_ungrammar", () => {
    // Smoke test: load ungrammar and parse a simple snippet
    const ptr = getLanguagePtr("ungrammar");
    expect(ptr).toBeTruthy();
  });

  it("smoke_uxntal", () => {
    // Smoke test: load uxntal and parse a simple snippet
    const ptr = getLanguagePtr("uxntal");
    expect(ptr).toBeTruthy();
  });

  it("smoke_v", () => {
    // Smoke test: load v and parse a simple snippet
    const ptr = getLanguagePtr("v");
    expect(ptr).toBeTruthy();
  });

  it("smoke_verilog", () => {
    // Smoke test: load verilog and parse a simple snippet
    const ptr = getLanguagePtr("verilog");
    expect(ptr).toBeTruthy();
  });

  it("smoke_vhdl", () => {
    // Smoke test: load vhdl and parse a simple snippet
    const ptr = getLanguagePtr("vhdl");
    expect(ptr).toBeTruthy();
  });

  it("smoke_vim", () => {
    // Smoke test: load vim and parse a simple snippet
    const ptr = getLanguagePtr("vim");
    expect(ptr).toBeTruthy();
  });

  it("smoke_vue", () => {
    // Smoke test: load vue and parse a simple snippet
    const ptr = getLanguagePtr("vue");
    expect(ptr).toBeTruthy();
  });

  it("smoke_wast", () => {
    // Smoke test: load wast and parse a simple snippet
    const ptr = getLanguagePtr("wast");
    expect(ptr).toBeTruthy();
  });

  it("smoke_wat", () => {
    // Smoke test: load wat and parse a simple snippet
    const ptr = getLanguagePtr("wat");
    expect(ptr).toBeTruthy();
  });

  it("smoke_wgsl", () => {
    // Smoke test: load wgsl and parse a simple snippet
    const ptr = getLanguagePtr("wgsl");
    expect(ptr).toBeTruthy();
  });

  it("smoke_xcompose", () => {
    // Smoke test: load xcompose and parse a simple snippet
    const ptr = getLanguagePtr("xcompose");
    expect(ptr).toBeTruthy();
  });

  it("smoke_xml", () => {
    // Smoke test: load xml and parse a simple snippet
    const ptr = getLanguagePtr("xml");
    expect(ptr).toBeTruthy();
  });

  it("smoke_yuck", () => {
    // Smoke test: load yuck and parse a simple snippet
    const ptr = getLanguagePtr("yuck");
    expect(ptr).toBeTruthy();
  });

  it("smoke_zig", () => {
    // Smoke test: load zig and parse a simple snippet
    const ptr = getLanguagePtr("zig");
    expect(ptr).toBeTruthy();
  });

});
