# Code generated by e2e-generator. DO NOT EDIT.

defmodule E2eTests.MixProject do
  use Mix.Project

  def project do
    [
      app: :e2e_tests,
      version: "0.0.0",
      elixir: "~> 1.15",
      deps: deps()
    ]
  end

  defp deps do
    [
      {:tree_sitter_language_pack, path: "../../crates/ts-pack-elixir"},
      {:jason, "~> 1.4"}
    ]
  end
end
