# Code generated by e2e-generator. DO NOT EDIT.

import pytest
import json

from tree_sitter_language_pack import get_language, get_parser, available_languages, has_language, process, process_and_chunk

from .helpers import tree_contains_node_type, tree_has_error_nodes


def test_smoke_actionscript():
    """Smoke test: load actionscript and parse a simple snippet"""
    parser = get_parser("actionscript")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_ada():
    """Smoke test: load ada and parse a simple snippet"""
    parser = get_parser("ada")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_agda():
    """Smoke test: load agda and parse a simple snippet"""
    parser = get_parser("agda")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_apex():
    """Smoke test: load apex and parse a simple snippet"""
    parser = get_parser("apex")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_arduino():
    """Smoke test: load arduino and parse a simple snippet"""
    parser = get_parser("arduino")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_asm():
    """Smoke test: load asm and parse a simple snippet"""
    parser = get_parser("asm")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_astro():
    """Smoke test: load astro and parse a simple snippet"""
    parser = get_parser("astro")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_bash():
    """Smoke test: load bash and parse a simple snippet"""
    parser = get_parser("bash")
    tree = parser.parse(b"echo hello")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_beancount():
    """Smoke test: load beancount and parse a simple snippet"""
    parser = get_parser("beancount")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_bibtex():
    """Smoke test: load bibtex and parse a simple snippet"""
    parser = get_parser("bibtex")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_bicep():
    """Smoke test: load bicep and parse a simple snippet"""
    parser = get_parser("bicep")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_bitbake():
    """Smoke test: load bitbake and parse a simple snippet"""
    parser = get_parser("bitbake")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_bsl():
    """Smoke test: load bsl and parse a simple snippet"""
    parser = get_parser("bsl")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_c():
    """Smoke test: load c and parse a simple snippet"""
    parser = get_parser("c")
    tree = parser.parse(b"int main() { return 0; }")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_cairo():
    """Smoke test: load cairo and parse a simple snippet"""
    parser = get_parser("cairo")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_capnp():
    """Smoke test: load capnp and parse a simple snippet"""
    parser = get_parser("capnp")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_chatito():
    """Smoke test: load chatito and parse a simple snippet"""
    parser = get_parser("chatito")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_clarity():
    """Smoke test: load clarity and parse a simple snippet"""
    parser = get_parser("clarity")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_clojure():
    """Smoke test: load clojure and parse a simple snippet"""
    parser = get_parser("clojure")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_cmake():
    """Smoke test: load cmake and parse a simple snippet"""
    parser = get_parser("cmake")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_cobol():
    """Smoke test: load cobol and parse a simple snippet"""
    parser = get_parser("cobol")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_comment():
    """Smoke test: load comment and parse a simple snippet"""
    parser = get_parser("comment")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_commonlisp():
    """Smoke test: load commonlisp and parse a simple snippet"""
    parser = get_parser("commonlisp")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_cpon():
    """Smoke test: load cpon and parse a simple snippet"""
    parser = get_parser("cpon")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_cpp():
    """Smoke test: load cpp and parse a simple snippet"""
    parser = get_parser("cpp")
    tree = parser.parse(b"int main() { return 0; }")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_css():
    """Smoke test: load css and parse a simple snippet"""
    parser = get_parser("css")
    tree = parser.parse(b"body { color: red; }")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_csv():
    """Smoke test: load csv and parse a simple snippet"""
    parser = get_parser("csv")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_cuda():
    """Smoke test: load cuda and parse a simple snippet"""
    parser = get_parser("cuda")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_d():
    """Smoke test: load d and parse a simple snippet"""
    parser = get_parser("d")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_dart():
    """Smoke test: load dart and parse a simple snippet"""
    parser = get_parser("dart")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_dockerfile():
    """Smoke test: load dockerfile and parse a simple snippet"""
    parser = get_parser("dockerfile")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_doxygen():
    """Smoke test: load doxygen and parse a simple snippet"""
    parser = get_parser("doxygen")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_dtd():
    """Smoke test: load dtd and parse a simple snippet"""
    parser = get_parser("dtd")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_elisp():
    """Smoke test: load elisp and parse a simple snippet"""
    parser = get_parser("elisp")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_elixir():
    """Smoke test: load elixir and parse a simple snippet"""
    parser = get_parser("elixir")
    tree = parser.parse(b"IO.puts(\"hello\")")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_elm():
    """Smoke test: load elm and parse a simple snippet"""
    parser = get_parser("elm")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_erlang():
    """Smoke test: load erlang and parse a simple snippet"""
    parser = get_parser("erlang")
    tree = parser.parse(b"main() -> ok.")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_fennel():
    """Smoke test: load fennel and parse a simple snippet"""
    parser = get_parser("fennel")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_firrtl():
    """Smoke test: load firrtl and parse a simple snippet"""
    parser = get_parser("firrtl")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_fish():
    """Smoke test: load fish and parse a simple snippet"""
    parser = get_parser("fish")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_fortran():
    """Smoke test: load fortran and parse a simple snippet"""
    parser = get_parser("fortran")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_fsharp():
    """Smoke test: load fsharp and parse a simple snippet"""
    parser = get_parser("fsharp")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_fsharp_signature():
    """Smoke test: load fsharp_signature and parse a simple snippet"""
    parser = get_parser("fsharp_signature")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_func():
    """Smoke test: load func and parse a simple snippet"""
    parser = get_parser("func")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_gdscript():
    """Smoke test: load gdscript and parse a simple snippet"""
    parser = get_parser("gdscript")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_gitattributes():
    """Smoke test: load gitattributes and parse a simple snippet"""
    parser = get_parser("gitattributes")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_gitcommit():
    """Smoke test: load gitcommit and parse a simple snippet"""
    parser = get_parser("gitcommit")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_gitignore():
    """Smoke test: load gitignore and parse a simple snippet"""
    parser = get_parser("gitignore")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_gleam():
    """Smoke test: load gleam and parse a simple snippet"""
    parser = get_parser("gleam")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_glsl():
    """Smoke test: load glsl and parse a simple snippet"""
    parser = get_parser("glsl")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_gn():
    """Smoke test: load gn and parse a simple snippet"""
    parser = get_parser("gn")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_go():
    """Smoke test: load go and parse a simple snippet"""
    parser = get_parser("go")
    tree = parser.parse(b"package main")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_gomod():
    """Smoke test: load gomod and parse a simple snippet"""
    parser = get_parser("gomod")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_gosum():
    """Smoke test: load gosum and parse a simple snippet"""
    parser = get_parser("gosum")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_graphql():
    """Smoke test: load graphql and parse a simple snippet"""
    parser = get_parser("graphql")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_groovy():
    """Smoke test: load groovy and parse a simple snippet"""
    parser = get_parser("groovy")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_gstlaunch():
    """Smoke test: load gstlaunch and parse a simple snippet"""
    parser = get_parser("gstlaunch")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_hack():
    """Smoke test: load hack and parse a simple snippet"""
    parser = get_parser("hack")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_hare():
    """Smoke test: load hare and parse a simple snippet"""
    parser = get_parser("hare")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_haskell():
    """Smoke test: load haskell and parse a simple snippet"""
    parser = get_parser("haskell")
    tree = parser.parse(b"main = putStrLn \"hello\"")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_haxe():
    """Smoke test: load haxe and parse a simple snippet"""
    parser = get_parser("haxe")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_hcl():
    """Smoke test: load hcl and parse a simple snippet"""
    parser = get_parser("hcl")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_heex():
    """Smoke test: load heex and parse a simple snippet"""
    parser = get_parser("heex")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_hlsl():
    """Smoke test: load hlsl and parse a simple snippet"""
    parser = get_parser("hlsl")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_html():
    """Smoke test: load html and parse a simple snippet"""
    parser = get_parser("html")
    tree = parser.parse(b"<p>hello</p>")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_hyprlang():
    """Smoke test: load hyprlang and parse a simple snippet"""
    parser = get_parser("hyprlang")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_ini():
    """Smoke test: load ini and parse a simple snippet"""
    parser = get_parser("ini")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_ispc():
    """Smoke test: load ispc and parse a simple snippet"""
    parser = get_parser("ispc")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_janet():
    """Smoke test: load janet and parse a simple snippet"""
    parser = get_parser("janet")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_java():
    """Smoke test: load java and parse a simple snippet"""
    parser = get_parser("java")
    tree = parser.parse(b"class Main {}")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_javascript():
    """Smoke test: load javascript and parse a simple snippet"""
    parser = get_parser("javascript")
    tree = parser.parse(b"console.log('hello');")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_jsdoc():
    """Smoke test: load jsdoc and parse a simple snippet"""
    parser = get_parser("jsdoc")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_json():
    """Smoke test: load json and parse a simple snippet"""
    parser = get_parser("json")
    tree = parser.parse(b"{\"key\": \"value\"}")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_jsonnet():
    """Smoke test: load jsonnet and parse a simple snippet"""
    parser = get_parser("jsonnet")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_julia():
    """Smoke test: load julia and parse a simple snippet"""
    parser = get_parser("julia")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_kconfig():
    """Smoke test: load kconfig and parse a simple snippet"""
    parser = get_parser("kconfig")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_kdl():
    """Smoke test: load kdl and parse a simple snippet"""
    parser = get_parser("kdl")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_kotlin():
    """Smoke test: load kotlin and parse a simple snippet"""
    parser = get_parser("kotlin")
    tree = parser.parse(b"fun main() {}")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_latex():
    """Smoke test: load latex and parse a simple snippet"""
    parser = get_parser("latex")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_linkerscript():
    """Smoke test: load linkerscript and parse a simple snippet"""
    parser = get_parser("linkerscript")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_llvm():
    """Smoke test: load llvm and parse a simple snippet"""
    parser = get_parser("llvm")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_lua():
    """Smoke test: load lua and parse a simple snippet"""
    parser = get_parser("lua")
    tree = parser.parse(b"print('hello')")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_luadoc():
    """Smoke test: load luadoc and parse a simple snippet"""
    parser = get_parser("luadoc")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_luap():
    """Smoke test: load luap and parse a simple snippet"""
    parser = get_parser("luap")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_luau():
    """Smoke test: load luau and parse a simple snippet"""
    parser = get_parser("luau")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_magik():
    """Smoke test: load magik and parse a simple snippet"""
    parser = get_parser("magik")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_make():
    """Smoke test: load make and parse a simple snippet"""
    parser = get_parser("make")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_markdown():
    """Smoke test: load markdown and parse a simple snippet"""
    parser = get_parser("markdown")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_markdown_inline():
    """Smoke test: load markdown_inline and parse a simple snippet"""
    parser = get_parser("markdown_inline")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_matlab():
    """Smoke test: load matlab and parse a simple snippet"""
    parser = get_parser("matlab")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_mermaid():
    """Smoke test: load mermaid and parse a simple snippet"""
    parser = get_parser("mermaid")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_meson():
    """Smoke test: load meson and parse a simple snippet"""
    parser = get_parser("meson")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_netlinx():
    """Smoke test: load netlinx and parse a simple snippet"""
    parser = get_parser("netlinx")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_nim():
    """Smoke test: load nim and parse a simple snippet"""
    parser = get_parser("nim")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_ninja():
    """Smoke test: load ninja and parse a simple snippet"""
    parser = get_parser("ninja")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_nix():
    """Smoke test: load nix and parse a simple snippet"""
    parser = get_parser("nix")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_nqc():
    """Smoke test: load nqc and parse a simple snippet"""
    parser = get_parser("nqc")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_objc():
    """Smoke test: load objc and parse a simple snippet"""
    parser = get_parser("objc")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_ocaml():
    """Smoke test: load ocaml and parse a simple snippet"""
    parser = get_parser("ocaml")
    tree = parser.parse(b"let () = print_endline \"hello\"")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_ocaml_interface():
    """Smoke test: load ocaml_interface and parse a simple snippet"""
    parser = get_parser("ocaml_interface")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_odin():
    """Smoke test: load odin and parse a simple snippet"""
    parser = get_parser("odin")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_org():
    """Smoke test: load org and parse a simple snippet"""
    parser = get_parser("org")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_pascal():
    """Smoke test: load pascal and parse a simple snippet"""
    parser = get_parser("pascal")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_pem():
    """Smoke test: load pem and parse a simple snippet"""
    parser = get_parser("pem")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_perl():
    """Smoke test: load perl and parse a simple snippet"""
    parser = get_parser("perl")
    tree = parser.parse(b"print 'hello';")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_pgn():
    """Smoke test: load pgn and parse a simple snippet"""
    parser = get_parser("pgn")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_php():
    """Smoke test: load php and parse a simple snippet"""
    parser = get_parser("php")
    tree = parser.parse(b"<?php echo 'hello'; ?>")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_po():
    """Smoke test: load po and parse a simple snippet"""
    parser = get_parser("po")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_pony():
    """Smoke test: load pony and parse a simple snippet"""
    parser = get_parser("pony")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_powershell():
    """Smoke test: load powershell and parse a simple snippet"""
    parser = get_parser("powershell")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_printf():
    """Smoke test: load printf and parse a simple snippet"""
    parser = get_parser("printf")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_prisma():
    """Smoke test: load prisma and parse a simple snippet"""
    parser = get_parser("prisma")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_properties():
    """Smoke test: load properties and parse a simple snippet"""
    parser = get_parser("properties")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_proto():
    """Smoke test: load proto and parse a simple snippet"""
    parser = get_parser("proto")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_psv():
    """Smoke test: load psv and parse a simple snippet"""
    parser = get_parser("psv")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_puppet():
    """Smoke test: load puppet and parse a simple snippet"""
    parser = get_parser("puppet")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_purescript():
    """Smoke test: load purescript and parse a simple snippet"""
    parser = get_parser("purescript")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_pymanifest():
    """Smoke test: load pymanifest and parse a simple snippet"""
    parser = get_parser("pymanifest")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_python():
    """Smoke test: load python and parse a simple snippet"""
    parser = get_parser("python")
    tree = parser.parse(b"print('hello')")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_qmldir():
    """Smoke test: load qmldir and parse a simple snippet"""
    parser = get_parser("qmldir")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_qmljs():
    """Smoke test: load qmljs and parse a simple snippet"""
    parser = get_parser("qmljs")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_query():
    """Smoke test: load query and parse a simple snippet"""
    parser = get_parser("query")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_r():
    """Smoke test: load r and parse a simple snippet"""
    parser = get_parser("r")
    tree = parser.parse(b"print('hello')")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_racket():
    """Smoke test: load racket and parse a simple snippet"""
    parser = get_parser("racket")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_re2c():
    """Smoke test: load re2c and parse a simple snippet"""
    parser = get_parser("re2c")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_readline():
    """Smoke test: load readline and parse a simple snippet"""
    parser = get_parser("readline")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_rego():
    """Smoke test: load rego and parse a simple snippet"""
    parser = get_parser("rego")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_requirements():
    """Smoke test: load requirements and parse a simple snippet"""
    parser = get_parser("requirements")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_ron():
    """Smoke test: load ron and parse a simple snippet"""
    parser = get_parser("ron")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_rst():
    """Smoke test: load rst and parse a simple snippet"""
    parser = get_parser("rst")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_ruby():
    """Smoke test: load ruby and parse a simple snippet"""
    parser = get_parser("ruby")
    tree = parser.parse(b"puts 'hello'")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_rust():
    """Smoke test: load rust and parse a simple snippet"""
    parser = get_parser("rust")
    tree = parser.parse(b"fn main() {}")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_scala():
    """Smoke test: load scala and parse a simple snippet"""
    parser = get_parser("scala")
    tree = parser.parse(b"object Main")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_scheme():
    """Smoke test: load scheme and parse a simple snippet"""
    parser = get_parser("scheme")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_scss():
    """Smoke test: load scss and parse a simple snippet"""
    parser = get_parser("scss")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_smali():
    """Smoke test: load smali and parse a simple snippet"""
    parser = get_parser("smali")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_smithy():
    """Smoke test: load smithy and parse a simple snippet"""
    parser = get_parser("smithy")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_solidity():
    """Smoke test: load solidity and parse a simple snippet"""
    parser = get_parser("solidity")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_sparql():
    """Smoke test: load sparql and parse a simple snippet"""
    parser = get_parser("sparql")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_sql():
    """Smoke test: load sql and parse a simple snippet"""
    parser = get_parser("sql")
    tree = parser.parse(b"SELECT 1;")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_squirrel():
    """Smoke test: load squirrel and parse a simple snippet"""
    parser = get_parser("squirrel")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_starlark():
    """Smoke test: load starlark and parse a simple snippet"""
    parser = get_parser("starlark")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_svelte():
    """Smoke test: load svelte and parse a simple snippet"""
    parser = get_parser("svelte")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_swift():
    """Smoke test: load swift and parse a simple snippet"""
    parser = get_parser("swift")
    tree = parser.parse(b"print(\"hello\")")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_tablegen():
    """Smoke test: load tablegen and parse a simple snippet"""
    parser = get_parser("tablegen")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_tcl():
    """Smoke test: load tcl and parse a simple snippet"""
    parser = get_parser("tcl")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_terraform():
    """Smoke test: load terraform and parse a simple snippet"""
    parser = get_parser("terraform")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_test():
    """Smoke test: load test and parse a simple snippet"""
    parser = get_parser("test")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_thrift():
    """Smoke test: load thrift and parse a simple snippet"""
    parser = get_parser("thrift")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_toml():
    """Smoke test: load toml and parse a simple snippet"""
    parser = get_parser("toml")
    tree = parser.parse(b"key = \"value\"")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_tsv():
    """Smoke test: load tsv and parse a simple snippet"""
    parser = get_parser("tsv")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_tsx():
    """Smoke test: load tsx and parse a simple snippet"""
    parser = get_parser("tsx")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_twig():
    """Smoke test: load twig and parse a simple snippet"""
    parser = get_parser("twig")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_typescript():
    """Smoke test: load typescript and parse a simple snippet"""
    parser = get_parser("typescript")
    tree = parser.parse(b"const x: number = 42;")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_typst():
    """Smoke test: load typst and parse a simple snippet"""
    parser = get_parser("typst")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_udev():
    """Smoke test: load udev and parse a simple snippet"""
    parser = get_parser("udev")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_ungrammar():
    """Smoke test: load ungrammar and parse a simple snippet"""
    parser = get_parser("ungrammar")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_uxntal():
    """Smoke test: load uxntal and parse a simple snippet"""
    parser = get_parser("uxntal")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_v():
    """Smoke test: load v and parse a simple snippet"""
    parser = get_parser("v")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_verilog():
    """Smoke test: load verilog and parse a simple snippet"""
    parser = get_parser("verilog")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_vhdl():
    """Smoke test: load vhdl and parse a simple snippet"""
    parser = get_parser("vhdl")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_vim():
    """Smoke test: load vim and parse a simple snippet"""
    parser = get_parser("vim")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_vue():
    """Smoke test: load vue and parse a simple snippet"""
    parser = get_parser("vue")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_wast():
    """Smoke test: load wast and parse a simple snippet"""
    parser = get_parser("wast")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_wat():
    """Smoke test: load wat and parse a simple snippet"""
    parser = get_parser("wat")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_wgsl():
    """Smoke test: load wgsl and parse a simple snippet"""
    parser = get_parser("wgsl")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_xcompose():
    """Smoke test: load xcompose and parse a simple snippet"""
    parser = get_parser("xcompose")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_xml():
    """Smoke test: load xml and parse a simple snippet"""
    parser = get_parser("xml")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_yuck():
    """Smoke test: load yuck and parse a simple snippet"""
    parser = get_parser("yuck")
    tree = parser.parse(b"x")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_zig():
    """Smoke test: load zig and parse a simple snippet"""
    parser = get_parser("zig")
    tree = parser.parse(b"pub fn main() void {}")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


