# Code generated by e2e-generator. DO NOT EDIT.

import pytest
import json

from tree_sitter_language_pack import get_language, get_parser, available_languages, has_language, process, process_and_chunk

from .helpers import tree_contains_node_type, tree_has_error_nodes


def test_parsing_go_function():
    """Parse a Go function declaration and assert node type"""
    parser = get_parser("go")
    tree = parser.parse(b"package main\nfunc main() {}")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert tree_contains_node_type(root, "function_declaration"), "Tree should contain a 'function_declaration' node"


def test_parsing_html_element():
    """Parse an HTML element and assert node type"""
    parser = get_parser("html")
    tree = parser.parse(b"<div>hello</div>")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert tree_contains_node_type(root, "element"), "Tree should contain a 'element' node"


def test_parsing_javascript_variable():
    """Parse a JavaScript variable declaration and assert node type"""
    parser = get_parser("javascript")
    tree = parser.parse(b"const x = 1;")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert tree_contains_node_type(root, "lexical_declaration"), "Tree should contain a 'lexical_declaration' node"


def test_parsing_python_function():
    """Parse a Python function definition and assert node type"""
    parser = get_parser("python")
    tree = parser.parse(b"def hello(): pass")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert tree_contains_node_type(root, "function_definition"), "Tree should contain a 'function_definition' node"


def test_parsing_rust_function():
    """Parse a Rust function definition and assert node type"""
    parser = get_parser("rust")
    tree = parser.parse(b"fn main() {}")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert tree_contains_node_type(root, "function_item"), "Tree should contain a 'function_item' node"


