# Code generated by e2e-generator. DO NOT EDIT.

import pytest
import json

from tree_sitter_language_pack import get_language, get_parser, available_languages, has_language, process, process_and_chunk

from .helpers import tree_contains_node_type, tree_has_error_nodes


@pytest.mark.skipif(not has_language("python"), reason="Language 'python' not available")
def test_python_chunking_intel():
    """Intel: chunk multi-function Python source into multiple pieces"""
    result_json = process_and_chunk("def alpha():\n    pass\n\ndef beta():\n    pass\n\ndef gamma():\n    pass\n\ndef delta():\n    pass\n", "python", 2)
    intel = json.loads(result_json)
    chunks = intel.get("chunks", [])
    assert len(chunks) >= 2, f"Should have at least 2 chunk(s), got {len(chunks)}"
    intel = intel.get("intelligence", {})
    assert intel.get("language") == "python", f"Expected language 'python', got {intel.get('language')}"
    metrics = intel.get("metrics", {})
    assert metrics.get("total_lines", 0) >= 8, f"Should have at least 8 total line(s)"


@pytest.mark.skipif(not has_language("python"), reason="Language 'python' not available")
def test_python_function_intel():
    """Intel: extract structure from Python function definition"""
    result_json = process("def greet(name):\n    return f'Hello, {name}!'\n", "python")
    intel = json.loads(result_json)
    assert intel.get("language") == "python", f"Expected language 'python', got {intel.get('language')}"
    assert len(intel.get("structure", [])) >= 1, f"Should have at least 1 structure(s)"
    assert any(s.get("kind") == "function" for s in intel.get("structure", [])), f"Structure should contain a 'function' kind node"
    metrics = intel.get("metrics", {})
    assert metrics.get("total_lines", 0) >= 2, f"Should have at least 2 total line(s)"
    metrics = intel.get("metrics", {})
    assert metrics.get("error_count", 0) == 0, f"Expected error_count 0, got {metrics.get('error_count', 0)}"


@pytest.mark.skipif(not has_language("rust"), reason="Language 'rust' not available")
def test_rust_function_intel():
    """Intel: extract structure from Rust function definition"""
    result_json = process("fn add(a: i32, b: i32) -> i32 {\n    a + b\n}\n", "rust")
    intel = json.loads(result_json)
    assert intel.get("language") == "rust", f"Expected language 'rust', got {intel.get('language')}"
    assert len(intel.get("structure", [])) >= 1, f"Should have at least 1 structure(s)"
    assert any(s.get("kind") == "function" for s in intel.get("structure", [])), f"Structure should contain a 'function' kind node"
    metrics = intel.get("metrics", {})
    assert metrics.get("total_lines", 0) >= 3, f"Should have at least 3 total line(s)"
    metrics = intel.get("metrics", {})
    assert metrics.get("error_count", 0) == 0, f"Expected error_count 0, got {metrics.get('error_count', 0)}"


