// Code generated by e2e-generator. DO NOT EDIT.

import { describe, it, expect } from "vitest";
import {
  availableLanguages,
  hasLanguage,
  getLanguagePtr,
  parseString,
  treeRootNodeType,
  treeRootChildCount,
  treeContainsNodeType,
  treeHasErrorNodes,
  freeTree,
  process,
  processAndChunk,
} from "./helpers";

describe("error_handling", () => {
  it("error_empty_language_name", () => {
    // Parsing with empty language name should error
    expect(() => getLanguagePtr("")).toThrow();
  });

  it("error_handling_empty_source", () => {
    // Parsing an empty string should still produce a tree.
    if (!hasLanguage("javascript")) {
      console.log("Skipping: language 'javascript' not available");
      return;
    }
    const tree = parseString("javascript", ``);
    expect(tree).toBeTruthy();
    expect(tree).not.toBeNull();
    freeTree(tree);
  });

  it("error_handling_invalid_syntax", () => {
    // Parsing invalid syntax should produce a tree with error nodes.
    if (!hasLanguage("javascript")) {
      console.log("Skipping: language 'javascript' not available");
      return;
    }
    const tree = parseString("javascript", `function function function @@@ %%%`);
    expect(tree).toBeTruthy();
    expect(tree).not.toBeNull();
    expect(treeHasErrorNodes(tree)).toBe(true);
    freeTree(tree);
  });

  it("error_handling_unknown_language", () => {
    // Loading a nonexistent language should produce an error.
    expect(() => getLanguagePtr("nonexistent_xyz")).toThrow();
  });

});
