// Code generated by e2e-generator. DO NOT EDIT.

// The nodejs wasm-pack target auto-initializes the WASM module on first require,
// so we simply re-export the functions — no manual init needed.
export {
  availableLanguages,
  hasLanguage,
  languageCount,
  getLanguagePtr,
  parseString,
  treeRootNodeType,
  treeRootChildCount,
  treeContainsNodeType,
  treeHasErrorNodes,
  freeTree,
  process,
  processAndChunk,
} from "@kreuzberg/tree-sitter-language-pack-wasm";
