// Code generated by e2e-generator. DO NOT EDIT.

import { describe, it, expect } from "vitest";
import {
  availableLanguages,
  hasLanguage,
  getLanguagePtr,
  parseString,
  treeRootNodeType,
  treeRootChildCount,
  treeContainsNodeType,
  treeHasErrorNodes,
  freeTree,
  process,
  processAndChunk,
} from "./helpers";

describe("metadata", () => {
  it("javascript_multi_import_metadata", () => {
    // Intel: detect multiple imports and function in JavaScript
    if (!hasLanguage("javascript")) {
      console.log("Skipping: language 'javascript' not available");
      return;
    }
    const tree = parseString("javascript", `import fs from 'fs';\nimport path from 'path';\n\nfunction process(input) {\n    return input.trim();\n}\n`);
    expect(tree).toBeTruthy();
    freeTree(tree);
  });

  it("meta_javascript_exports_detail", () => {
    // JavaScript with exports, verify export count
    if (!hasLanguage("javascript")) {
      console.log("Skipping: language 'javascript' not available");
      return;
    }
    const tree = parseString("javascript", `export function greet(name) {\n  return \`Hello \${name}\`;\n}\n\nexport const VERSION = '1.0';\n`);
    expect(tree).toBeTruthy();
    expect(tree).not.toBeNull();
    freeTree(tree);
  });

  it("typescript_function_metadata", () => {
    // Intel: extract structure from TypeScript function
    if (!hasLanguage("typescript")) {
      console.log("Skipping: language 'typescript' not available");
      return;
    }
    const tree = parseString("typescript", `import { readFile } from 'fs';\n\nfunction greet(name: string): string {\n    return \`Hello, \${name}!\`;\n}\n`);
    expect(tree).toBeTruthy();
    freeTree(tree);
  });

});
