# Code generated by e2e-generator. DO NOT EDIT.

require_relative "spec_helper"

RSpec.describe "intel" do

  it "python_chunking_intel" do
    # Intel: chunk multi-function Python source into multiple pieces
    skip "Language 'python' not available" unless TreeSitterLanguagePack.has_language("python")
    result_json = TreeSitterLanguagePack.process_and_chunk("def alpha():\n    pass\n\ndef beta():\n    pass\n\ndef gamma():\n    pass\n\ndef delta():\n    pass\n", "python", 30)
    result = JSON.parse(result_json)
    intel = result["intelligence"]
    chunks = result["chunks"]
    expect(intel["language"]).to eq("python")
    expect(intel["metrics"]["total_lines"]).to be >= 8
    expect(chunks.length).to be >= 2
  end

  it "python_function_intel" do
    # Intel: extract structure from Python function definition
    skip "Language 'python' not available" unless TreeSitterLanguagePack.has_language("python")
    result_json = TreeSitterLanguagePack.process("def greet(name):\n    return f'Hello, {name}!'\n", "python")
    intel = JSON.parse(result_json)
    expect(intel["language"]).to eq("python")
    expect(intel["structure"].length).to be >= 1
    expect(intel["structure"].any? { |s| s["kind"] == "function" }).to be true
    expect(intel["metrics"]["total_lines"]).to be >= 2
    expect(intel["metrics"]["error_count"]).to eq(0)
  end

  it "rust_function_intel" do
    # Intel: extract structure from Rust function definition
    skip "Language 'rust' not available" unless TreeSitterLanguagePack.has_language("rust")
    result_json = TreeSitterLanguagePack.process("fn add(a: i32, b: i32) -> i32 {\n    a + b\n}\n", "rust")
    intel = JSON.parse(result_json)
    expect(intel["language"]).to eq("rust")
    expect(intel["structure"].length).to be >= 1
    expect(intel["structure"].any? { |s| s["kind"] == "function" }).to be true
    expect(intel["metrics"]["total_lines"]).to be >= 3
    expect(intel["metrics"]["error_count"]).to eq(0)
  end
end
