#ifndef TS_PACK_H
#define TS_PACK_H

/* This file is auto-generated by cbindgen. Do not edit manually. */

#include <stddef.h>
#include <stdbool.h>
#include <stdint.h>
/* Forward declaration for tree-sitter's TSLanguage type */
typedef struct TSLanguage TSLanguage;

/**
 * Opaque handle to a language registry.
 * Created with `ts_pack_registry_new` and freed with `ts_pack_registry_free`.
 */
typedef struct TsPackRegistry TsPackRegistry;

/**
 * Opaque handle to a parsed syntax tree.
 * Created with `ts_pack_parse_string` and freed with `ts_pack_tree_free`.
 */
typedef struct TsPackTree TsPackTree;

/**
 * Create a new language registry.
 *
 * Returns a pointer to the registry, or null on failure.
 * The caller must free the registry with `ts_pack_registry_free`.
 *
 * # Safety
 *
 * The returned pointer must be freed with `ts_pack_registry_free`.
 */
struct TsPackRegistry *ts_pack_registry_new(void);

/**
 * Free a registry previously created with `ts_pack_registry_new`.
 *
 * Passing a null pointer is a safe no-op.
 *
 * # Safety
 *
 * `registry` must be a pointer returned by `ts_pack_registry_new`, or null.
 */
void ts_pack_registry_free(struct TsPackRegistry *registry);

/**
 * Get a raw `TSLanguage` pointer for the given language name.
 *
 * Returns null on error (check `ts_pack_last_error` for details).
 * The returned pointer is valid for the lifetime of the registry.
 *
 * # Safety
 *
 * `registry` must be a valid pointer returned by `ts_pack_registry_new`, or null.
 * `name` must be a valid null-terminated UTF-8 C string, or null.
 */
const TSLanguage *ts_pack_get_language(const struct TsPackRegistry *registry, const char *name);

/**
 * Return the number of available languages.
 *
 * Returns 0 if the registry pointer is null.
 *
 * # Safety
 *
 * `registry` must be a valid pointer returned by `ts_pack_registry_new`, or null.
 */
uintptr_t ts_pack_language_count(const struct TsPackRegistry *registry);

/**
 * Get the language name at the given index.
 *
 * Returns a newly-allocated C string that the caller must free with
 * `ts_pack_free_string`. Returns null if the index is out of bounds or
 * the registry pointer is null.
 *
 * # Safety
 *
 * `registry` must be a valid pointer returned by `ts_pack_registry_new`, or null.
 */
const char *ts_pack_language_name_at(const struct TsPackRegistry *registry, uintptr_t index);

/**
 * Check whether the registry contains a language with the given name.
 *
 * Returns false if the registry or name pointer is null.
 *
 * # Safety
 *
 * `registry` must be a valid pointer returned by `ts_pack_registry_new`, or null.
 * `name` must be a valid null-terminated UTF-8 C string, or null.
 */
bool ts_pack_has_language(const struct TsPackRegistry *registry, const char *name);

/**
 * Get the last error message, or null if no error occurred.
 *
 * The returned pointer is valid until the next FFI call on the same thread.
 * The caller must NOT free this pointer.
 *
 * # Safety
 *
 * The returned pointer is only valid until the next FFI call on the same thread.
 */
const char *ts_pack_last_error(void);

/**
 * Clear the last error.
 *
 * # Safety
 *
 * This function is always safe to call.
 */
void ts_pack_clear_error(void);

/**
 * Free a string that was returned by the FFI (e.g. from `ts_pack_language_name_at`).
 *
 * Passing a null pointer is a safe no-op.
 *
 * # Safety
 *
 * `s` must be a pointer returned by an FFI function in this crate, or null.
 */
void ts_pack_free_string(char *s);

/**
 * Parse a source string using the named language and return an opaque tree handle.
 *
 * Returns null on error (check `ts_pack_last_error` for details).
 * The caller must free the tree with `ts_pack_tree_free`.
 *
 * # Safety
 *
 * `registry` must be a valid pointer returned by `ts_pack_registry_new`.
 * `name` and `source` must be valid null-terminated UTF-8 C strings.
 */
struct TsPackTree *ts_pack_parse_string(const struct TsPackRegistry *registry,
                                        const char *name,
                                        const char *source,
                                        uintptr_t source_len);

/**
 * Free a tree previously created with `ts_pack_parse_string`.
 *
 * Passing a null pointer is a safe no-op.
 *
 * # Safety
 *
 * `tree` must be a pointer returned by `ts_pack_parse_string`, or null.
 */
void ts_pack_tree_free(struct TsPackTree *tree);

/**
 * Get the type name of the root node of the tree.
 *
 * Returns a newly-allocated C string that the caller must free with
 * `ts_pack_free_string`. Returns null if the tree pointer is null.
 *
 * # Safety
 *
 * `tree` must be a valid pointer returned by `ts_pack_parse_string`, or null.
 */
char *ts_pack_tree_root_node_type(const struct TsPackTree *tree);

/**
 * Get the number of named children of the root node.
 *
 * Returns 0 if the tree pointer is null.
 *
 * # Safety
 *
 * `tree` must be a valid pointer returned by `ts_pack_parse_string`, or null.
 */
uint32_t ts_pack_tree_root_child_count(const struct TsPackTree *tree);

/**
 * Check whether any node in the tree has the given type name.
 *
 * Uses a depth-first traversal via TreeCursor.
 *
 * # Safety
 *
 * `tree` must be a valid pointer returned by `ts_pack_parse_string`, or null.
 * `node_type` must be a valid null-terminated UTF-8 C string, or null.
 */
bool ts_pack_tree_contains_node_type(const struct TsPackTree *tree, const char *node_type);

/**
 * Check whether the tree contains any ERROR or MISSING nodes.
 *
 * # Safety
 *
 * `tree` must be a valid pointer returned by `ts_pack_parse_string`, or null.
 */
bool ts_pack_tree_has_error_nodes(const struct TsPackTree *tree);

/**
 * Return the S-expression representation of the tree.
 *
 * Returns a newly-allocated C string that the caller must free with
 * `ts_pack_free_string`. Returns null if the tree pointer is null.
 *
 * # Safety
 *
 * `tree` must be a valid pointer returned by `ts_pack_parse_string`, or null.
 */
char *ts_pack_tree_to_sexp(const struct TsPackTree *tree);

/**
 * Return the count of ERROR and MISSING nodes in the tree.
 *
 * Returns 0 if the tree pointer is null.
 *
 * # Safety
 *
 * `tree` must be a valid pointer returned by `ts_pack_parse_string`, or null.
 */
uintptr_t ts_pack_tree_error_count(const struct TsPackTree *tree);

/**
 * Process source code and extract file intelligence as a JSON C string.
 *
 * Returns a newly-allocated C string that the caller must free with
 * `ts_pack_free_string`. Returns null on error (check `ts_pack_last_error`).
 *
 * # Safety
 *
 * `registry` must be a valid pointer returned by `ts_pack_registry_new`.
 * `source` must be a valid pointer to `source_len` bytes.
 * `language` must be a valid null-terminated UTF-8 C string.
 */
char *ts_pack_process(const struct TsPackRegistry *registry,
                      const char *source,
                      uintptr_t source_len,
                      const char *language);

/**
 * Process and chunk source code, returning intelligence + chunks as a JSON C string.
 *
 * Returns a newly-allocated C string that the caller must free with
 * `ts_pack_free_string`. Returns null on error (check `ts_pack_last_error`).
 *
 * # Safety
 *
 * `registry` must be a valid pointer returned by `ts_pack_registry_new`.
 * `source` must be a valid pointer to `source_len` bytes.
 * `language` must be a valid null-terminated UTF-8 C string.
 */
char *ts_pack_process_and_chunk(const struct TsPackRegistry *registry,
                                const char *source,
                                uintptr_t source_len,
                                const char *language,
                                uintptr_t max_chunk_size);

#endif  /* TS_PACK_H */
