use crate::fixtures::{Fixture, escape_c_string, sanitize_name};
use crate::generators::Generator;
use std::fmt::Write as FmtWrite;
use std::path::Path;

pub struct CGenerator;

impl Generator for CGenerator {
    fn name(&self) -> &'static str {
        "C"
    }

    fn generate(&self, fixtures: &[Fixture], output_dir: &Path) -> Result<(), String> {
        let c_dir = output_dir.join("c");
        std::fs::create_dir_all(&c_dir).map_err(|e| format!("Failed to create c output dir: {e}"))?;

        write_cmake_lists(&c_dir, fixtures)?;
        write_helpers_h(&c_dir)?;

        for fixture in fixtures {
            write_test_file(&c_dir, fixture)?;
        }

        Ok(())
    }
}

fn write_cmake_lists(dir: &Path, fixtures: &[Fixture]) -> Result<(), String> {
    let mut content = String::from(
        r#"# Code generated by e2e-generator. DO NOT EDIT.

cmake_minimum_required(VERSION 3.20)
project(e2e_tests C)

set(CMAKE_C_STANDARD 11)

# Find ts_pack_ffi
set(FFI_DIR "${CMAKE_CURRENT_SOURCE_DIR}/../../crates/ts-pack-ffi")
set(FFI_INCLUDE "${FFI_DIR}/include")
set(FFI_LIB_DIR "${CMAKE_CURRENT_SOURCE_DIR}/../../target/release")

include_directories(${FFI_INCLUDE})
link_directories(${FFI_LIB_DIR})

enable_testing()

"#,
    );

    // One executable + CTest per fixture
    for fixture in fixtures {
        let name = sanitize_name(&fixture.id);
        writeln!(content, "add_executable(test_{name} test_{name}.c)").unwrap();
        writeln!(content, "target_link_libraries(test_{name} ts_pack_ffi)").unwrap();
        writeln!(content, "add_test(NAME test_{name} COMMAND test_{name})").unwrap();
        writeln!(content).unwrap();
    }

    std::fs::write(dir.join("CMakeLists.txt"), &content).map_err(|e| format!("Failed to write CMakeLists.txt: {e}"))
}

fn write_helpers_h(dir: &Path) -> Result<(), String> {
    let content = r#"/* Code generated by e2e-generator. DO NOT EDIT. */

#ifndef E2E_HELPERS_H
#define E2E_HELPERS_H

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ts_pack.h"

#define ASSERT_TRUE(expr, msg) \
    do { \
        if (!(expr)) { \
            fprintf(stderr, "FAIL: %s (line %d): %s\n", __func__, __LINE__, (msg)); \
            exit(1); \
        } \
    } while (0)

#define ASSERT_FALSE(expr, msg) \
    do { \
        if ((expr)) { \
            fprintf(stderr, "FAIL: %s (line %d): %s\n", __func__, __LINE__, (msg)); \
            exit(1); \
        } \
    } while (0)

#define ASSERT_NOT_NULL(ptr, msg) \
    do { \
        if ((ptr) == NULL) { \
            fprintf(stderr, "FAIL: %s (line %d): %s\n", __func__, __LINE__, (msg)); \
            exit(1); \
        } \
    } while (0)

#define ASSERT_NULL(ptr, msg) \
    do { \
        if ((ptr) != NULL) { \
            fprintf(stderr, "FAIL: %s (line %d): %s\n", __func__, __LINE__, (msg)); \
            exit(1); \
        } \
    } while (0)

#define ASSERT_GT(a, b, msg) \
    do { \
        if (!((a) > (b))) { \
            fprintf(stderr, "FAIL: %s (line %d): %s (got %zu <= %zu)\n", __func__, __LINE__, (msg), (size_t)(a), (size_t)(b)); \
            exit(1); \
        } \
    } while (0)

#define ASSERT_EQ_BOOL(a, b, msg) \
    do { \
        if ((a) != (b)) { \
            fprintf(stderr, "FAIL: %s (line %d): %s (got %d, want %d)\n", __func__, __LINE__, (msg), (int)(a), (int)(b)); \
            exit(1); \
        } \
    } while (0)

#define TEST_PASS() \
    printf("PASS: %s\n", __func__)

#endif /* E2E_HELPERS_H */
"#;
    std::fs::write(dir.join("helpers.h"), content).map_err(|e| format!("Failed to write helpers.h: {e}"))
}

fn has_intel_assertions(fixture: &Fixture) -> bool {
    fixture.assertions.as_ref().is_some_and(|a| {
        a.intel_language.is_some()
            || a.intel_structure_count_min.is_some()
            || a.intel_structure_contains_kind.is_some()
            || a.intel_imports_count_min.is_some()
            || a.intel_metrics_total_lines_min.is_some()
            || a.intel_metrics_error_count.is_some()
            || a.intel_diagnostics_not_empty.is_some()
            || a.intel_chunk_count_min.is_some()
    })
}

fn has_chunk_assertions(fixture: &Fixture) -> bool {
    fixture
        .assertions
        .as_ref()
        .is_some_and(|a| a.intel_chunk_count_min.is_some())
}

fn write_test_file(dir: &Path, fixture: &Fixture) -> Result<(), String> {
    let mut out = String::new();
    let fn_name = format!("test_{}", sanitize_name(&fixture.id));
    let assertions = fixture.assertions.as_ref();

    writeln!(out, "/* Code generated by e2e-generator. DO NOT EDIT. */").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "#include \"helpers.h\"").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "int main(void) {{").unwrap();
    writeln!(out, "    /* {} */", fixture.description).unwrap();

    writeln!(out, "    TsPackRegistry *reg = ts_pack_registry_new();").unwrap();
    writeln!(out, "    ASSERT_NOT_NULL(reg, \"Failed to create registry\");").unwrap();

    // Skip logic
    if let Some(skip) = &fixture.skip
        && let Some(req_lang) = &skip.requires_language
    {
        writeln!(
            out,
            "    if (!ts_pack_has_language(reg, \"{}\")) {{",
            escape_c_string(req_lang)
        )
        .unwrap();
        writeln!(
            out,
            "        printf(\"SKIP: {} (language '{}' not available)\\n\");",
            fn_name,
            escape_c_string(req_lang)
        )
        .unwrap();
        writeln!(out, "        ts_pack_registry_free(reg);").unwrap();
        writeln!(out, "        return 0;").unwrap();
        writeln!(out, "    }}").unwrap();
    }

    if assertions.is_some_and(|a| a.expect_error == Some(true)) {
        if let Some(lang) = &fixture.language {
            writeln!(
                out,
                "    const TSLanguage *lang = ts_pack_get_language(reg, \"{}\");",
                escape_c_string(lang)
            )
            .unwrap();
            writeln!(out, "    ASSERT_NULL(lang, \"Expected NULL for unknown language\");").unwrap();
        }
    } else if assertions.is_some_and(|a| a.languages_not_empty == Some(true)) {
        writeln!(out, "    uintptr_t count = ts_pack_language_count(reg);").unwrap();
        writeln!(out, "    ASSERT_GT(count, 0, \"language_count should be > 0\");").unwrap();
    } else if assertions.is_some_and(|a| a.language_available.is_some()) {
        let expected = assertions.unwrap().language_available.unwrap();
        let lang = fixture.language.as_deref().unwrap_or("unknown");
        writeln!(
            out,
            "    bool result = ts_pack_has_language(reg, \"{}\");",
            escape_c_string(lang)
        )
        .unwrap();
        writeln!(out, "    ASSERT_EQ_BOOL(result, {}, \"has_language check\");", expected).unwrap();
    } else if has_intel_assertions(fixture) {
        let lang = fixture.language.as_deref().unwrap_or("unknown");
        let source = fixture.source_code.as_deref().unwrap_or("");
        let source_escaped = escape_c_string(source);

        if has_chunk_assertions(fixture) {
            let max_chunk_size = assertions.unwrap().intel_chunk_max_size.unwrap_or(512);
            writeln!(
                out,
                "    char *result = ts_pack_process_and_chunk(reg, \"{}\", {}, \"{}\", {});",
                source_escaped,
                source.len(),
                escape_c_string(lang),
                max_chunk_size
            )
            .unwrap();
        } else {
            writeln!(
                out,
                "    char *result = ts_pack_process(reg, \"{}\", {}, \"{}\");",
                source_escaped,
                source.len(),
                escape_c_string(lang)
            )
            .unwrap();
        }
        writeln!(out, "    ASSERT_NOT_NULL(result, \"process returned NULL\");").unwrap();
        writeln!(out, "    /* Verify JSON string is non-empty */").unwrap();
        writeln!(
            out,
            "    ASSERT_TRUE(strlen(result) > 2, \"JSON result should not be empty\");"
        )
        .unwrap();
        writeln!(out, "    ts_pack_free_string(result);").unwrap();
    } else if let Some(lang) = &fixture.language {
        writeln!(
            out,
            "    const TSLanguage *lang = ts_pack_get_language(reg, \"{}\");",
            escape_c_string(lang)
        )
        .unwrap();
        writeln!(
            out,
            "    ASSERT_NOT_NULL(lang, \"Language pointer should not be NULL\");"
        )
        .unwrap();
    }

    writeln!(out, "    ts_pack_registry_free(reg);").unwrap();
    writeln!(out, "    printf(\"PASS: {}\\n\");", fn_name).unwrap();
    writeln!(out, "    return 0;").unwrap();
    writeln!(out, "}}").unwrap();

    let filename = format!("{fn_name}.c");
    std::fs::write(dir.join(&filename), &out).map_err(|e| format!("Failed to write {filename}: {e}"))
}
