use crate::fixtures::{
    Fixture, escape_csharp_string, group_by_category, has_chunk_assertions, has_intel_assertions, sanitize_name,
};
use crate::generators::Generator;
use std::fmt::Write as FmtWrite;
use std::path::Path;

pub struct CSharpGenerator;

impl Generator for CSharpGenerator {
    fn name(&self) -> &'static str {
        "C#"
    }

    fn generate(&self, fixtures: &[Fixture], output_dir: &Path) -> Result<(), String> {
        let cs_dir = output_dir.join("csharp");

        // Clean stale test files before writing new ones
        let _ = std::fs::remove_dir_all(&cs_dir);

        std::fs::create_dir_all(&cs_dir).map_err(|e| format!("Failed to create csharp output dir: {e}"))?;

        write_csproj(&cs_dir)?;

        let groups = group_by_category(fixtures);
        for (category, cat_fixtures) in &groups {
            write_test_file(&cs_dir, category, cat_fixtures)?;
        }

        Ok(())
    }
}

fn write_csproj(dir: &Path) -> Result<(), String> {
    let content = r#"<!-- Code generated by e2e-generator. DO NOT EDIT. -->
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../packages/csharp/TreeSitterLanguagePack/TreeSitterLanguagePack.csproj" />
  </ItemGroup>

</Project>
"#;
    std::fs::write(dir.join("E2ETests.csproj"), content).map_err(|e| format!("Failed to write E2ETests.csproj: {e}"))
}

fn write_test_file(dir: &Path, category: &str, fixtures: &[&Fixture]) -> Result<(), String> {
    let class_name = to_csharp_class_name(category);
    let mut out = String::new();

    writeln!(out, "// Code generated by e2e-generator. DO NOT EDIT.").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "using Xunit;").unwrap();
    writeln!(out, "using TreeSitterLanguagePack;").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "namespace E2E.Tests;").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "public class {class_name}Tests").unwrap();
    writeln!(out, "{{").unwrap();

    for fixture in fixtures {
        let method_name = to_csharp_method_name(&fixture.id);
        let assertions = fixture.assertions.as_ref();

        // Auto-skip: guard any test that requires a specific language.
        let is_availability_agnostic = assertions.is_some_and(|a| {
            a.expect_error == Some(true) || a.language_available.is_some() || a.languages_not_empty == Some(true)
        });
        let skip_lang = fixture.skip.as_ref().and_then(|s| s.requires_language.as_deref()).or({
            if !is_availability_agnostic {
                fixture.language.as_deref()
            } else {
                None
            }
        });

        writeln!(out).unwrap();
        if skip_lang.is_some() {
            writeln!(out, "    [Fact]").unwrap();
        } else {
            writeln!(out, "    [Fact]").unwrap();
        }
        writeln!(out, "    public void {}()", method_name).unwrap();
        writeln!(out, "    {{").unwrap();
        writeln!(out, "        // {}", fixture.description).unwrap();

        if let Some(lang) = skip_lang {
            writeln!(
                out,
                "        if (!TsPackClient.HasLanguage(\"{}\"))",
                escape_csharp_string(lang)
            )
            .unwrap();
            writeln!(out, "        {{").unwrap();
            writeln!(
                out,
                "            return; // Language '{}' not available",
                escape_csharp_string(lang)
            )
            .unwrap();
            writeln!(out, "        }}").unwrap();
        }

        if assertions.is_some_and(|a| a.expect_error == Some(true)) {
            if let Some(lang) = &fixture.language {
                writeln!(
                    out,
                    "        Assert.ThrowsAny<Exception>(() => TsPackClient.GetLanguage(\"{}\"));",
                    escape_csharp_string(lang)
                )
                .unwrap();
            }
        } else if assertions.is_some_and(|a| a.languages_not_empty == Some(true)) {
            writeln!(out, "        var langs = TsPackClient.AvailableLanguages();").unwrap();
            writeln!(out, "        Assert.NotEmpty(langs);").unwrap();
        } else if assertions.is_some_and(|a| a.language_available.is_some()) {
            let expected = assertions.unwrap().language_available.unwrap();
            let lang = fixture.language.as_deref().unwrap_or("unknown");
            writeln!(
                out,
                "        Assert.{}(TsPackClient.HasLanguage(\"{}\"));",
                if expected { "True" } else { "False" },
                escape_csharp_string(lang)
            )
            .unwrap();
        } else if has_intel_assertions(fixture) {
            let lang = fixture.language.as_deref().unwrap_or("unknown");
            let source = fixture.source_code.as_deref().unwrap_or("");
            let assertions = assertions.unwrap();

            if has_chunk_assertions(fixture) {
                let max_chunk_size = assertions.intel_chunk_max_size.unwrap_or(512);
                writeln!(
                    out,
                    "        var config = new ProcessConfig {{ Language = \"{}\", ChunkMaxSize = {} }};",
                    escape_csharp_string(lang),
                    max_chunk_size
                )
                .unwrap();
            } else {
                writeln!(
                    out,
                    "        var config = new ProcessConfig {{ Language = \"{}\" }};",
                    escape_csharp_string(lang)
                )
                .unwrap();
            }
            writeln!(
                out,
                "        var result = TsPackClient.Process(\"{}\", config);",
                escape_csharp_string(source)
            )
            .unwrap();

            if let Some(expected_lang) = &assertions.intel_language {
                writeln!(
                    out,
                    "        Assert.Equal(\"{}\", result.Language);",
                    escape_csharp_string(expected_lang)
                )
                .unwrap();
            }

            if let Some(min_structures) = assertions.intel_structure_count_min {
                writeln!(
                    out,
                    "        Assert.True(result.Structure.Count >= {}, \"Should have at least {} structure(s)\");",
                    min_structures, min_structures
                )
                .unwrap();
            }

            if let Some(expected_kind) = &assertions.intel_structure_contains_kind {
                writeln!(
                    out,
                    "        Assert.Contains(result.Structure, s => s.Kind.ToString() == \"{}\");",
                    escape_csharp_string(expected_kind)
                )
                .unwrap();
            }

            if let Some(min_imports) = assertions.intel_imports_count_min {
                writeln!(
                    out,
                    "        Assert.True(result.Imports.Count >= {}, \"Should have at least {} import(s)\");",
                    min_imports, min_imports
                )
                .unwrap();
            }

            if let Some(min_lines) = assertions.intel_metrics_total_lines_min {
                writeln!(
                    out,
                    "        Assert.True(result.Metrics.TotalLines >= {}, \"Should have at least {} total line(s)\");",
                    min_lines, min_lines
                )
                .unwrap();
            }

            if let Some(expected_error_count) = assertions.intel_metrics_error_count {
                writeln!(
                    out,
                    "        Assert.Equal({}, result.Metrics.ErrorCount);",
                    expected_error_count
                )
                .unwrap();
            }

            if assertions.intel_diagnostics_not_empty == Some(true) {
                writeln!(out, "        Assert.NotEmpty(result.Diagnostics);").unwrap();
            }

            if has_chunk_assertions(fixture)
                && let Some(min_chunks) = assertions.intel_chunk_count_min
            {
                writeln!(
                    out,
                    "        Assert.True(result.Chunks.Count >= {}, \"Should have at least {} chunk(s)\");",
                    min_chunks, min_chunks
                )
                .unwrap();
            }
        } else if let Some(lang) = &fixture.language {
            writeln!(
                out,
                "        var langPtr = TsPackClient.GetLanguage(\"{}\");",
                escape_csharp_string(lang)
            )
            .unwrap();
            writeln!(
                out,
                "        Assert.True(langPtr != IntPtr.Zero, \"Language pointer should not be null\");"
            )
            .unwrap();
        }

        writeln!(out, "    }}").unwrap();
    }

    writeln!(out, "}}").unwrap();

    let filename = format!("{class_name}Tests.cs");
    std::fs::write(dir.join(&filename), &out).map_err(|e| format!("Failed to write {filename}: {e}"))
}

/// Convert a category name to a C# PascalCase class name.
fn to_csharp_class_name(category: &str) -> String {
    let sanitized = sanitize_name(category);
    let mut result = String::new();
    let mut capitalize_next = true;

    for c in sanitized.chars() {
        if c == '_' {
            capitalize_next = true;
        } else if capitalize_next {
            result.push(c.to_ascii_uppercase());
            capitalize_next = false;
        } else {
            result.push(c);
        }
    }

    result
}

/// Convert a fixture ID to a C# PascalCase method name.
fn to_csharp_method_name(id: &str) -> String {
    let sanitized = sanitize_name(id);
    let mut result = String::new();
    let mut capitalize_next = true;

    for c in sanitized.chars() {
        if c == '_' {
            capitalize_next = true;
        } else if capitalize_next {
            result.push(c.to_ascii_uppercase());
            capitalize_next = false;
        } else {
            result.push(c);
        }
    }

    result
}
