use crate::fixtures::{Fixture, escape_elixir_string, group_by_category, sanitize_name};
use crate::generators::Generator;
use std::fmt::Write as FmtWrite;
use std::path::Path;

pub struct ElixirGenerator;

impl Generator for ElixirGenerator {
    fn name(&self) -> &'static str {
        "Elixir"
    }

    fn generate(&self, fixtures: &[Fixture], output_dir: &Path) -> Result<(), String> {
        let ex_dir = output_dir.join("elixir");
        std::fs::create_dir_all(ex_dir.join("test")).map_err(|e| format!("Failed to create elixir output dir: {e}"))?;

        write_mix_exs(&ex_dir)?;
        write_test_helper(&ex_dir)?;

        let groups = group_by_category(fixtures);
        for (category, cat_fixtures) in &groups {
            write_test_file(&ex_dir, category, cat_fixtures)?;
        }

        Ok(())
    }
}

fn write_mix_exs(dir: &Path) -> Result<(), String> {
    let content = r#"# Code generated by e2e-generator. DO NOT EDIT.

defmodule E2eTests.MixProject do
  use Mix.Project

  def project do
    [
      app: :e2e_tests,
      version: "0.0.0",
      elixir: "~> 1.15",
      deps: deps()
    ]
  end

  defp deps do
    [
      {:tree_sitter_language_pack, path: "../../crates/ts-pack-elixir"},
      {:jason, "~> 1.4"}
    ]
  end
end
"#;
    std::fs::write(dir.join("mix.exs"), content).map_err(|e| format!("Failed to write mix.exs: {e}"))
}

fn write_test_helper(dir: &Path) -> Result<(), String> {
    let content = r#"# Code generated by e2e-generator. DO NOT EDIT.

ExUnit.start()
"#;
    std::fs::write(dir.join("test").join("test_helper.exs"), content)
        .map_err(|e| format!("Failed to write test_helper.exs: {e}"))
}

fn has_intel_assertions(fixture: &Fixture) -> bool {
    if let Some(assertions) = &fixture.assertions {
        assertions.intel_language.is_some()
            || assertions.intel_structure_count_min.is_some()
            || assertions.intel_structure_contains_kind.is_some()
            || assertions.intel_imports_count_min.is_some()
            || assertions.intel_metrics_total_lines_min.is_some()
            || assertions.intel_metrics_error_count.is_some()
            || assertions.intel_diagnostics_not_empty.is_some()
            || assertions.intel_chunk_count_min.is_some()
    } else {
        false
    }
}

fn has_chunk_assertions(fixture: &Fixture) -> bool {
    if let Some(assertions) = &fixture.assertions {
        assertions.intel_chunk_count_min.is_some() || assertions.intel_chunk_max_size.is_some()
    } else {
        false
    }
}

fn write_test_file(dir: &Path, category: &str, fixtures: &[&Fixture]) -> Result<(), String> {
    let mut out = String::new();
    let module_name = to_elixir_module_name(category);

    writeln!(out, "# Code generated by e2e-generator. DO NOT EDIT.").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "defmodule E2eTests.{module_name}Test do").unwrap();
    writeln!(out, "  use ExUnit.Case, async: true").unwrap();
    writeln!(out).unwrap();

    for fixture in fixtures {
        let test_name = sanitize_name(&fixture.id);
        let assertions = fixture.assertions.as_ref();

        // Skip logic via tag
        if let Some(skip) = &fixture.skip
            && let Some(req_lang) = &skip.requires_language
        {
            writeln!(out, "  @tag :skip_unless_{}", sanitize_name(req_lang)).unwrap();
        }

        writeln!(out, "  test \"{}\" do", test_name).unwrap();
        writeln!(out, "    # {}", fixture.description).unwrap();

        // Skip logic check
        if let Some(skip) = &fixture.skip
            && let Some(req_lang) = &skip.requires_language
        {
            writeln!(
                out,
                "    unless TreeSitterLanguagePack.has_language(\"{}\") do",
                escape_elixir_string(req_lang)
            )
            .unwrap();
            writeln!(
                out,
                "      IO.puts(\"Skipping: language '{}' not available\")",
                escape_elixir_string(req_lang)
            )
            .unwrap();
            writeln!(out, "    else").unwrap();
        }

        if assertions.is_some_and(|a| a.expect_error == Some(true)) {
            if let Some(lang) = &fixture.language {
                writeln!(out, "    assert_raise ErlangError, fn ->").unwrap();
                writeln!(
                    out,
                    "      TreeSitterLanguagePack.get_language_ptr(\"{}\")",
                    escape_elixir_string(lang)
                )
                .unwrap();
                writeln!(out, "    end").unwrap();
            }
        } else if assertions.is_some_and(|a| a.languages_not_empty == Some(true)) {
            writeln!(out, "    langs = TreeSitterLanguagePack.available_languages()").unwrap();
            writeln!(
                out,
                "    assert length(langs) > 0, \"available_languages() should not be empty\""
            )
            .unwrap();
        } else if assertions.is_some_and(|a| a.language_available.is_some()) {
            let expected = assertions.unwrap().language_available.unwrap();
            let lang = fixture.language.as_deref().unwrap_or("unknown");
            writeln!(
                out,
                "    assert TreeSitterLanguagePack.has_language(\"{}\") == {}",
                escape_elixir_string(lang),
                expected
            )
            .unwrap();
        } else if has_intel_assertions(fixture) {
            let lang = fixture.language.as_deref().unwrap_or("unknown");
            let source = fixture.source_code.as_deref().unwrap_or("");

            if has_chunk_assertions(fixture) {
                let chunk_size = assertions.and_then(|a| a.intel_chunk_max_size).unwrap_or(1024);
                writeln!(
                    out,
                    "    result_json = TreeSitterLanguagePack.process_and_chunk(\"{}\", \"{}\", {})",
                    escape_elixir_string(source),
                    escape_elixir_string(lang),
                    chunk_size
                )
                .unwrap();
                writeln!(out, "    result = Jason.decode!(result_json)").unwrap();
                writeln!(out, "    intel = result[\"intelligence\"]").unwrap();
                writeln!(out, "    chunks = result[\"chunks\"]").unwrap();
            } else {
                writeln!(
                    out,
                    "    result_json = TreeSitterLanguagePack.process(\"{}\", \"{}\")",
                    escape_elixir_string(source),
                    escape_elixir_string(lang)
                )
                .unwrap();
                writeln!(out, "    intel = Jason.decode!(result_json)").unwrap();
            }

            if let Some(expected_lang) = assertions.and_then(|a| a.intel_language.as_deref()) {
                writeln!(
                    out,
                    "    assert intel[\"language\"] == \"{}\"",
                    escape_elixir_string(expected_lang)
                )
                .unwrap();
            }

            if let Some(min_count) = assertions.and_then(|a| a.intel_structure_count_min) {
                writeln!(out, "    assert length(intel[\"structure\"]) >= {}", min_count).unwrap();
            }

            if let Some(kind) = assertions.and_then(|a| a.intel_structure_contains_kind.as_deref()) {
                writeln!(
                    out,
                    "    assert Enum.any?(intel[\"structure\"], fn s -> s[\"kind\"] == \"{}\" end)",
                    escape_elixir_string(kind)
                )
                .unwrap();
            }

            if let Some(min_count) = assertions.and_then(|a| a.intel_imports_count_min) {
                writeln!(out, "    assert length(intel[\"imports\"]) >= {}", min_count).unwrap();
            }

            if let Some(min_lines) = assertions.and_then(|a| a.intel_metrics_total_lines_min) {
                writeln!(out, "    assert intel[\"metrics\"][\"total_lines\"] >= {}", min_lines).unwrap();
            }

            if let Some(error_count) = assertions.and_then(|a| a.intel_metrics_error_count) {
                writeln!(out, "    assert intel[\"metrics\"][\"error_count\"] == {}", error_count).unwrap();
            }

            if assertions.is_some_and(|a| a.intel_diagnostics_not_empty == Some(true)) {
                writeln!(out, "    assert length(intel[\"diagnostics\"]) > 0").unwrap();
            }

            if has_chunk_assertions(fixture)
                && let Some(min_chunks) = assertions.and_then(|a| a.intel_chunk_count_min)
            {
                writeln!(out, "    assert length(chunks) >= {}", min_chunks).unwrap();
            }
        } else if let Some(lang) = &fixture.language {
            // Parsing test: use parse_string and tree inspection functions
            let source = fixture.source_code.as_deref().unwrap_or("");
            writeln!(
                out,
                "    tree = TreeSitterLanguagePack.parse_string(\"{}\", \"{}\")",
                escape_elixir_string(lang),
                escape_elixir_string(source)
            )
            .unwrap();

            if assertions.is_some_and(|a| a.tree_not_null == Some(true)) {
                writeln!(
                    out,
                    "    assert is_reference(tree), \"Parse tree should be a reference\""
                )
                .unwrap();

                if let Some(min_children) = assertions.and_then(|a| a.root_child_count_min) {
                    writeln!(
                        out,
                        "    child_count = TreeSitterLanguagePack.tree_root_child_count(tree)"
                    )
                    .unwrap();
                    writeln!(
                        out,
                        "    assert child_count >= {min_children}, \"Root should have at least {min_children} child(ren), got #{{child_count}}\""
                    )
                    .unwrap();
                }

                if let Some(node_type) = assertions.and_then(|a| a.root_contains_node_type.as_deref()) {
                    writeln!(
                        out,
                        "    assert TreeSitterLanguagePack.tree_contains_node_type(tree, \"{}\"), \"Tree should contain a '{}' node\"",
                        escape_elixir_string(node_type),
                        escape_elixir_string(node_type)
                    )
                    .unwrap();
                }

                if assertions.is_some_and(|a| a.has_error_nodes == Some(true)) {
                    writeln!(
                        out,
                        "    assert TreeSitterLanguagePack.tree_has_error_nodes(tree), \"Tree should contain error nodes\""
                    )
                    .unwrap();
                }
            } else {
                // If no tree_not_null assertion, just verify the tree is a valid reference
                writeln!(
                    out,
                    "    assert is_reference(tree), \"Parse tree should be a reference\""
                )
                .unwrap();
            }
        }

        // Close skip block
        if fixture.skip.as_ref().is_some_and(|s| s.requires_language.is_some()) {
            writeln!(out, "    end").unwrap();
        }

        writeln!(out, "  end").unwrap();
        writeln!(out).unwrap();
    }

    writeln!(out, "end").unwrap();

    let filename = format!("{}_test.exs", sanitize_name(category));
    std::fs::write(dir.join("test").join(&filename), &out).map_err(|e| format!("Failed to write {filename}: {e}"))
}

/// Convert a category name to an Elixir PascalCase module name.
fn to_elixir_module_name(category: &str) -> String {
    let sanitized = sanitize_name(category);
    let mut result = String::new();
    let mut capitalize_next = true;

    for c in sanitized.chars() {
        if c == '_' {
            capitalize_next = true;
        } else if capitalize_next {
            result.push(c.to_ascii_uppercase());
            capitalize_next = false;
        } else {
            result.push(c);
        }
    }

    result
}
