use crate::fixtures::{Fixture, escape_go_string, group_by_category, sanitize_name};
use crate::generators::Generator;
use std::fmt::Write as FmtWrite;
use std::path::Path;

pub struct GoGenerator;

impl Generator for GoGenerator {
    fn name(&self) -> &'static str {
        "Go"
    }

    fn generate(&self, fixtures: &[Fixture], output_dir: &Path) -> Result<(), String> {
        let go_dir = output_dir.join("go");
        std::fs::create_dir_all(&go_dir).map_err(|e| format!("Failed to create go output dir: {e}"))?;

        write_go_mod(&go_dir)?;
        write_helpers_test_go(&go_dir)?;

        let groups = group_by_category(fixtures);
        for (category, cat_fixtures) in &groups {
            write_test_file(&go_dir, category, cat_fixtures)?;
        }

        Ok(())
    }
}

fn write_go_mod(dir: &Path) -> Result<(), String> {
    let content = r#"// Code generated by e2e-generator. DO NOT EDIT.

module e2e_tests

go 1.22

require github.com/kreuzberg-dev/tree-sitter-language-pack/crates/ts-pack-go v0.0.0

replace github.com/kreuzberg-dev/tree-sitter-language-pack/crates/ts-pack-go => ../../crates/ts-pack-go
"#;
    std::fs::write(dir.join("go.mod"), content).map_err(|e| format!("Failed to write go.mod: {e}"))
}

fn write_helpers_test_go(dir: &Path) -> Result<(), String> {
    let content = r#"// Code generated by e2e-generator. DO NOT EDIT.

package e2e_tests

import (
	"testing"

	tspack "github.com/kreuzberg-dev/tree-sitter-language-pack/crates/ts-pack-go"
)

// newTestRegistry creates a registry for testing and registers cleanup.
func newTestRegistry(t *testing.T) *tspack.Registry {
	t.Helper()

	reg, err := tspack.NewRegistry()
	if err != nil {
		t.Fatalf("Failed to create registry: %v", err)
	}
	t.Cleanup(func() { reg.Close() })

	return reg
}

// skipIfLanguageUnavailable skips the test if the given language is not available.
func skipIfLanguageUnavailable(t *testing.T, reg *tspack.Registry, lang string) {
	t.Helper()

	if !reg.HasLanguage(lang) {
		t.Skipf("Language %q not available", lang)
	}
}
"#;
    std::fs::write(dir.join("helpers_test.go"), content).map_err(|e| format!("Failed to write helpers_test.go: {e}"))
}

fn write_test_file(dir: &Path, category: &str, fixtures: &[&Fixture]) -> Result<(), String> {
    let mut out = String::new();

    writeln!(out, "// Code generated by e2e-generator. DO NOT EDIT.").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "package e2e_tests").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "import \"testing\"").unwrap();
    writeln!(out).unwrap();

    for fixture in fixtures {
        let fn_name = to_go_test_name(&fixture.id);
        let assertions = fixture.assertions.as_ref();

        writeln!(out, "func {fn_name}(t *testing.T) {{").unwrap();
        writeln!(out, "\t// {}", fixture.description).unwrap();

        // Skip logic
        if let Some(skip) = &fixture.skip
            && let Some(req_lang) = &skip.requires_language
        {
            writeln!(out, "\treg := newTestRegistry(t)").unwrap();
            writeln!(
                out,
                "\tskipIfLanguageUnavailable(t, reg, \"{}\")",
                escape_go_string(req_lang)
            )
            .unwrap();
        }

        if assertions.is_some_and(|a| a.expect_error == Some(true)) {
            if let Some(lang) = &fixture.language {
                writeln!(out, "\treg := newTestRegistry(t)").unwrap();
                writeln!(out, "\t_, err := reg.GetLanguage(\"{}\")", escape_go_string(lang)).unwrap();
                writeln!(out, "\tif err == nil {{").unwrap();
                writeln!(
                    out,
                    "\t\tt.Fatalf(\"Expected error loading language %q, got nil\", \"{}\")",
                    escape_go_string(lang)
                )
                .unwrap();
                writeln!(out, "\t}}").unwrap();
            }
        } else if assertions.is_some_and(|a| a.languages_not_empty == Some(true)) {
            writeln!(out, "\treg := newTestRegistry(t)").unwrap();
            writeln!(out, "\tlangs := reg.AvailableLanguages()").unwrap();
            writeln!(out, "\tif len(langs) == 0 {{").unwrap();
            writeln!(out, "\t\tt.Fatal(\"AvailableLanguages() should not be empty\")").unwrap();
            writeln!(out, "\t}}").unwrap();
        } else if assertions.is_some_and(|a| a.language_available.is_some()) {
            let expected = assertions.unwrap().language_available.unwrap();
            let lang = fixture.language.as_deref().unwrap_or("unknown");
            writeln!(out, "\treg := newTestRegistry(t)").unwrap();
            writeln!(out, "\tgot := reg.HasLanguage(\"{}\")", escape_go_string(lang)).unwrap();
            writeln!(out, "\tif got != {} {{", expected).unwrap();
            writeln!(
                out,
                "\t\tt.Fatalf(\"HasLanguage(%q) = %v, want %v\", \"{}\", got, {})",
                escape_go_string(lang),
                expected
            )
            .unwrap();
            writeln!(out, "\t}}").unwrap();
        } else if let Some(lang) = &fixture.language {
            writeln!(out, "\treg := newTestRegistry(t)").unwrap();
            writeln!(out, "\tptr, err := reg.GetLanguage(\"{}\")", escape_go_string(lang)).unwrap();
            writeln!(out, "\tif err != nil {{").unwrap();
            writeln!(
                out,
                "\t\tt.Fatalf(\"Failed to get language %q: %v\", \"{}\", err)",
                escape_go_string(lang)
            )
            .unwrap();
            writeln!(out, "\t}}").unwrap();
            writeln!(out, "\tif ptr == nil {{").unwrap();
            writeln!(
                out,
                "\t\tt.Fatalf(\"Language pointer for %q is nil\", \"{}\")",
                escape_go_string(lang)
            )
            .unwrap();
            writeln!(out, "\t}}").unwrap();
        }

        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();
    }

    let filename = format!("{}_test.go", sanitize_name(category));
    std::fs::write(dir.join(&filename), &out).map_err(|e| format!("Failed to write {filename}: {e}"))
}

/// Convert a fixture id to a Go test function name (PascalCase with Test prefix).
fn to_go_test_name(id: &str) -> String {
    let sanitized = sanitize_name(id);
    let mut result = String::from("Test");
    let mut capitalize_next = true;

    for c in sanitized.chars() {
        if c == '_' {
            capitalize_next = true;
        } else if capitalize_next {
            result.push(c.to_ascii_uppercase());
            capitalize_next = false;
        } else {
            result.push(c);
        }
    }

    result
}
