use crate::fixtures::{Fixture, escape_go_string, group_by_category, sanitize_name};
use crate::generators::Generator;
use std::fmt::Write as FmtWrite;
use std::path::Path;

pub struct GoGenerator;

impl Generator for GoGenerator {
    fn name(&self) -> &'static str {
        "Go"
    }

    fn generate(&self, fixtures: &[Fixture], output_dir: &Path) -> Result<(), String> {
        let go_dir = output_dir.join("go");
        std::fs::create_dir_all(&go_dir).map_err(|e| format!("Failed to create go output dir: {e}"))?;

        write_go_mod(&go_dir)?;
        write_helpers_test_go(&go_dir)?;

        let groups = group_by_category(fixtures);
        for (category, cat_fixtures) in &groups {
            write_test_file(&go_dir, category, cat_fixtures)?;
        }

        Ok(())
    }
}

fn write_go_mod(dir: &Path) -> Result<(), String> {
    let content = r#"// Code generated by e2e-generator. DO NOT EDIT.

module e2e_tests

go 1.22

require github.com/kreuzberg-dev/tree-sitter-language-pack/crates/ts-pack-go v0.0.0

replace github.com/kreuzberg-dev/tree-sitter-language-pack/crates/ts-pack-go => ../../crates/ts-pack-go
"#;
    std::fs::write(dir.join("go.mod"), content).map_err(|e| format!("Failed to write go.mod: {e}"))
}

fn write_helpers_test_go(dir: &Path) -> Result<(), String> {
    let content = r#"// Code generated by e2e-generator. DO NOT EDIT.

package e2e_tests

import (
	"testing"

	tspack "github.com/kreuzberg-dev/tree-sitter-language-pack/crates/ts-pack-go"
)

// newTestRegistry creates a registry for testing and registers cleanup.
func newTestRegistry(t *testing.T) *tspack.Registry {
	t.Helper()

	reg, err := tspack.NewRegistry()
	if err != nil {
		t.Fatalf("Failed to create registry: %v", err)
	}
	t.Cleanup(func() { reg.Close() })

	return reg
}

// skipIfLanguageUnavailable skips the test if the given language is not available.
func skipIfLanguageUnavailable(t *testing.T, reg *tspack.Registry, lang string) {
	t.Helper()

	if !reg.HasLanguage(lang) {
		t.Skipf("Language %q not available", lang)
	}
}
"#;
    std::fs::write(dir.join("helpers_test.go"), content).map_err(|e| format!("Failed to write helpers_test.go: {e}"))
}

fn has_intel_assertions(fixture: &Fixture) -> bool {
    fixture.assertions.as_ref().is_some_and(|a| {
        a.intel_language.is_some()
            || a.intel_structure_count_min.is_some()
            || a.intel_structure_contains_kind.is_some()
            || a.intel_imports_count_min.is_some()
            || a.intel_metrics_total_lines_min.is_some()
            || a.intel_metrics_error_count.is_some()
            || a.intel_diagnostics_not_empty.is_some()
            || a.intel_chunk_count_min.is_some()
    })
}

fn has_chunk_assertions(fixture: &Fixture) -> bool {
    fixture
        .assertions
        .as_ref()
        .is_some_and(|a| a.intel_chunk_count_min.is_some())
}

fn write_test_file(dir: &Path, category: &str, fixtures: &[&Fixture]) -> Result<(), String> {
    let needs_json = fixtures.iter().any(|f| has_intel_assertions(f));

    let mut out = String::new();

    writeln!(out, "// Code generated by e2e-generator. DO NOT EDIT.").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "package e2e_tests").unwrap();
    writeln!(out).unwrap();
    if needs_json {
        writeln!(out, "import (").unwrap();
        writeln!(out, "\t\"encoding/json\"").unwrap();
        writeln!(out, "\t\"testing\"").unwrap();
        writeln!(out, ")").unwrap();
    } else {
        writeln!(out, "import \"testing\"").unwrap();
    }
    writeln!(out).unwrap();

    for fixture in fixtures {
        let fn_name = to_go_test_name(&fixture.id);
        let assertions = fixture.assertions.as_ref();

        writeln!(out, "func {fn_name}(t *testing.T) {{").unwrap();
        writeln!(out, "\t// {}", fixture.description).unwrap();

        // Skip logic
        if let Some(skip) = &fixture.skip
            && let Some(req_lang) = &skip.requires_language
        {
            writeln!(out, "\treg := newTestRegistry(t)").unwrap();
            writeln!(
                out,
                "\tskipIfLanguageUnavailable(t, reg, \"{}\")",
                escape_go_string(req_lang)
            )
            .unwrap();
        }

        if assertions.is_some_and(|a| a.expect_error == Some(true)) {
            if let Some(lang) = &fixture.language {
                writeln!(out, "\treg := newTestRegistry(t)").unwrap();
                writeln!(out, "\t_, err := reg.GetLanguage(\"{}\")", escape_go_string(lang)).unwrap();
                writeln!(out, "\tif err == nil {{").unwrap();
                writeln!(
                    out,
                    "\t\tt.Fatalf(\"Expected error loading language %q, got nil\", \"{}\")",
                    escape_go_string(lang)
                )
                .unwrap();
                writeln!(out, "\t}}").unwrap();
            }
        } else if assertions.is_some_and(|a| a.languages_not_empty == Some(true)) {
            writeln!(out, "\treg := newTestRegistry(t)").unwrap();
            writeln!(out, "\tlangs := reg.AvailableLanguages()").unwrap();
            writeln!(out, "\tif len(langs) == 0 {{").unwrap();
            writeln!(out, "\t\tt.Fatal(\"AvailableLanguages() should not be empty\")").unwrap();
            writeln!(out, "\t}}").unwrap();
        } else if assertions.is_some_and(|a| a.language_available.is_some()) {
            let expected = assertions.unwrap().language_available.unwrap();
            let lang = fixture.language.as_deref().unwrap_or("unknown");
            writeln!(out, "\treg := newTestRegistry(t)").unwrap();
            writeln!(out, "\tgot := reg.HasLanguage(\"{}\")", escape_go_string(lang)).unwrap();
            writeln!(out, "\tif got != {} {{", expected).unwrap();
            writeln!(
                out,
                "\t\tt.Fatalf(\"HasLanguage(%q) = %v, want %v\", \"{}\", got, {})",
                escape_go_string(lang),
                expected
            )
            .unwrap();
            writeln!(out, "\t}}").unwrap();
        } else if has_intel_assertions(fixture) {
            let lang = fixture.language.as_deref().unwrap_or("unknown");
            let source = fixture.source_code.as_deref().unwrap_or("");
            let assertions = assertions.unwrap();

            writeln!(out, "\treg := newTestRegistry(t)").unwrap();

            if has_chunk_assertions(fixture) {
                let max_chunk_size = assertions.intel_chunk_max_size.unwrap_or(512);
                writeln!(
                    out,
                    "\tresultJSON, err := reg.ProcessAndChunk(\"{}\", \"{}\", {})",
                    escape_go_string(source),
                    escape_go_string(lang),
                    max_chunk_size
                )
                .unwrap();
            } else {
                writeln!(
                    out,
                    "\tresultJSON, err := reg.Process(\"{}\", \"{}\")",
                    escape_go_string(source),
                    escape_go_string(lang)
                )
                .unwrap();
            }
            writeln!(out, "\tif err != nil {{").unwrap();
            writeln!(out, "\t\tt.Fatalf(\"process failed: %v\", err)").unwrap();
            writeln!(out, "\t}}").unwrap();
            writeln!(out).unwrap();
            writeln!(out, "\tvar intel map[string]interface{{}}").unwrap();
            writeln!(
                out,
                "\tif err := json.Unmarshal([]byte(resultJSON), &intel); err != nil {{"
            )
            .unwrap();
            writeln!(out, "\t\tt.Fatalf(\"failed to unmarshal JSON: %v\", err)").unwrap();
            writeln!(out, "\t}}").unwrap();

            if has_chunk_assertions(fixture) {
                if let Some(min_chunks) = assertions.intel_chunk_count_min {
                    writeln!(out).unwrap();
                    writeln!(out, "\tchunks, _ := intel[\"chunks\"].([]interface{{}})").unwrap();
                    writeln!(out, "\tif len(chunks) < {} {{", min_chunks).unwrap();
                    writeln!(
                        out,
                        "\t\tt.Fatalf(\"expected at least {} chunk(s), got %d\", len(chunks))",
                        min_chunks
                    )
                    .unwrap();
                    writeln!(out, "\t}}").unwrap();
                }
                writeln!(
                    out,
                    "\tif intelObj, ok := intel[\"intelligence\"].(map[string]interface{{}}); ok {{"
                )
                .unwrap();
                writeln!(out, "\t\tintel = intelObj").unwrap();
                writeln!(out, "\t}}").unwrap();
            }

            if let Some(expected_lang) = &assertions.intel_language {
                writeln!(out).unwrap();
                writeln!(
                    out,
                    "\tif lang, _ := intel[\"language\"].(string); lang != \"{}\" {{",
                    escape_go_string(expected_lang)
                )
                .unwrap();
                writeln!(
                    out,
                    "\t\tt.Fatalf(\"expected language %q, got %q\", \"{}\", lang)",
                    escape_go_string(expected_lang)
                )
                .unwrap();
                writeln!(out, "\t}}").unwrap();
            }

            if let Some(min_structures) = assertions.intel_structure_count_min {
                writeln!(out).unwrap();
                writeln!(out, "\tstructure, _ := intel[\"structure\"].([]interface{{}})").unwrap();
                writeln!(out, "\tif len(structure) < {} {{", min_structures).unwrap();
                writeln!(
                    out,
                    "\t\tt.Fatalf(\"expected at least {} structure(s), got %d\", len(structure))",
                    min_structures
                )
                .unwrap();
                writeln!(out, "\t}}").unwrap();
            }

            if let Some(expected_kind) = &assertions.intel_structure_contains_kind {
                writeln!(out).unwrap();
                writeln!(out, "\tstructureList, _ := intel[\"structure\"].([]interface{{}})").unwrap();
                writeln!(out, "\tfoundKind := false").unwrap();
                writeln!(out, "\tfor _, s := range structureList {{").unwrap();
                writeln!(out, "\t\tif m, ok := s.(map[string]interface{{}}); ok {{").unwrap();
                writeln!(
                    out,
                    "\t\t\tif k, _ := m[\"kind\"].(string); k == \"{}\" {{",
                    escape_go_string(expected_kind)
                )
                .unwrap();
                writeln!(out, "\t\t\t\tfoundKind = true").unwrap();
                writeln!(out, "\t\t\t\tbreak").unwrap();
                writeln!(out, "\t\t\t}}").unwrap();
                writeln!(out, "\t\t}}").unwrap();
                writeln!(out, "\t}}").unwrap();
                writeln!(out, "\tif !foundKind {{").unwrap();
                writeln!(
                    out,
                    "\t\tt.Fatal(\"structure should contain a '{}' kind node\")",
                    escape_go_string(expected_kind)
                )
                .unwrap();
                writeln!(out, "\t}}").unwrap();
            }

            if let Some(min_imports) = assertions.intel_imports_count_min {
                writeln!(out).unwrap();
                writeln!(out, "\timports, _ := intel[\"imports\"].([]interface{{}})").unwrap();
                writeln!(out, "\tif len(imports) < {} {{", min_imports).unwrap();
                writeln!(
                    out,
                    "\t\tt.Fatalf(\"expected at least {} import(s), got %d\", len(imports))",
                    min_imports
                )
                .unwrap();
                writeln!(out, "\t}}").unwrap();
            }

            if let Some(min_lines) = assertions.intel_metrics_total_lines_min {
                writeln!(out).unwrap();
                writeln!(out, "\tmetrics, _ := intel[\"metrics\"].(map[string]interface{{}})").unwrap();
                writeln!(out, "\ttotalLines, _ := metrics[\"total_lines\"].(float64)").unwrap();
                writeln!(out, "\tif int(totalLines) < {} {{", min_lines).unwrap();
                writeln!(
                    out,
                    "\t\tt.Fatalf(\"expected at least {} total line(s), got %v\", totalLines)",
                    min_lines
                )
                .unwrap();
                writeln!(out, "\t}}").unwrap();
            }

            if let Some(expected_error_count) = assertions.intel_metrics_error_count {
                writeln!(out).unwrap();
                writeln!(out, "\tmetricsMap, _ := intel[\"metrics\"].(map[string]interface{{}})").unwrap();
                writeln!(out, "\terrorCount, _ := metricsMap[\"error_count\"].(float64)").unwrap();
                writeln!(out, "\tif int(errorCount) != {} {{", expected_error_count).unwrap();
                writeln!(
                    out,
                    "\t\tt.Fatalf(\"expected error_count {}, got %v\", errorCount)",
                    expected_error_count
                )
                .unwrap();
                writeln!(out, "\t}}").unwrap();
            }

            if assertions.intel_diagnostics_not_empty == Some(true) {
                writeln!(out).unwrap();
                writeln!(out, "\tdiagnostics, _ := intel[\"diagnostics\"].([]interface{{}})").unwrap();
                writeln!(out, "\tif len(diagnostics) == 0 {{").unwrap();
                writeln!(out, "\t\tt.Fatal(\"diagnostics should not be empty\")").unwrap();
                writeln!(out, "\t}}").unwrap();
            }
        } else if let Some(lang) = &fixture.language {
            writeln!(out, "\treg := newTestRegistry(t)").unwrap();
            writeln!(out, "\tptr, err := reg.GetLanguage(\"{}\")", escape_go_string(lang)).unwrap();
            writeln!(out, "\tif err != nil {{").unwrap();
            writeln!(
                out,
                "\t\tt.Fatalf(\"Failed to get language %q: %v\", \"{}\", err)",
                escape_go_string(lang)
            )
            .unwrap();
            writeln!(out, "\t}}").unwrap();
            writeln!(out, "\tif ptr == nil {{").unwrap();
            writeln!(
                out,
                "\t\tt.Fatalf(\"Language pointer for %q is nil\", \"{}\")",
                escape_go_string(lang)
            )
            .unwrap();
            writeln!(out, "\t}}").unwrap();
        }

        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();
    }

    let filename = format!("{}_test.go", sanitize_name(category));
    std::fs::write(dir.join(&filename), &out).map_err(|e| format!("Failed to write {filename}: {e}"))
}

/// Convert a fixture id to a Go test function name (PascalCase with Test prefix).
fn to_go_test_name(id: &str) -> String {
    let sanitized = sanitize_name(id);
    let mut result = String::from("Test");
    let mut capitalize_next = true;

    for c in sanitized.chars() {
        if c == '_' {
            capitalize_next = true;
        } else if capitalize_next {
            result.push(c.to_ascii_uppercase());
            capitalize_next = false;
        } else {
            result.push(c);
        }
    }

    result
}
