use crate::fixtures::{Fixture, escape_java_string, group_by_category, sanitize_name};
use crate::generators::Generator;
use std::fmt::Write as FmtWrite;
use std::path::Path;

pub struct JavaGenerator;

impl Generator for JavaGenerator {
    fn name(&self) -> &'static str {
        "Java"
    }

    fn generate(&self, fixtures: &[Fixture], output_dir: &Path) -> Result<(), String> {
        let java_dir = output_dir.join("java");
        let test_pkg = java_dir.join("src/test/java/io/github/treesitter/languagepack/e2e");
        std::fs::create_dir_all(&test_pkg).map_err(|e| format!("Failed to create java output dir: {e}"))?;

        write_pom_xml(&java_dir)?;
        write_helpers_java(&test_pkg)?;

        let groups = group_by_category(fixtures);
        for (category, cat_fixtures) in &groups {
            write_test_file(&test_pkg, category, cat_fixtures)?;
        }

        Ok(())
    }
}

fn write_pom_xml(dir: &Path) -> Result<(), String> {
    let content = r#"<?xml version="1.0" encoding="UTF-8"?>
<!-- Code generated by e2e-generator. DO NOT EDIT. -->
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>io.github.treesitter</groupId>
    <artifactId>e2e-tests</artifactId>
    <version>0.0.0</version>

    <properties>
        <maven.compiler.source>22</maven.compiler.source>
        <maven.compiler.target>22</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.5.2</version>
                <configuration>
                    <argLine>--enable-native-access=ALL-UNNAMED</argLine>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>io.github.treesitter</groupId>
            <artifactId>tree-sitter-language-pack</artifactId>
            <version>0.0.0</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/../../crates/ts-pack-java/target/tree-sitter-language-pack.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <version>5.11.0</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
"#;
    std::fs::write(dir.join("pom.xml"), content).map_err(|e| format!("Failed to write pom.xml: {e}"))
}

fn write_helpers_java(pkg_dir: &Path) -> Result<(), String> {
    let content = r#"// Code generated by e2e-generator. DO NOT EDIT.

package io.github.treesitter.languagepack.e2e;

import io.github.treesitter.languagepack.TsPackRegistry;

/**
 * Shared helpers for E2E tests.
 */
final class Helpers {

    private Helpers() {}

    /**
     * Create a new registry, failing the test if creation fails.
     */
    static TsPackRegistry createRegistry() {
        return new TsPackRegistry();
    }
}
"#;
    std::fs::write(pkg_dir.join("Helpers.java"), content).map_err(|e| format!("Failed to write Helpers.java: {e}"))
}

fn has_intel_assertions(fixture: &Fixture) -> bool {
    fixture.assertions.as_ref().is_some_and(|a| {
        a.intel_language.is_some()
            || a.intel_structure_count_min.is_some()
            || a.intel_structure_contains_kind.is_some()
            || a.intel_imports_count_min.is_some()
            || a.intel_metrics_total_lines_min.is_some()
            || a.intel_metrics_error_count.is_some()
            || a.intel_diagnostics_not_empty.is_some()
            || a.intel_chunk_count_min.is_some()
    })
}

fn has_chunk_assertions(fixture: &Fixture) -> bool {
    fixture
        .assertions
        .as_ref()
        .is_some_and(|a| a.intel_chunk_count_min.is_some())
}

fn write_test_file(pkg_dir: &Path, category: &str, fixtures: &[&Fixture]) -> Result<(), String> {
    let needs_json = fixtures.iter().any(|f| has_intel_assertions(f));

    let mut out = String::new();
    let class_name = to_java_class_name(category);

    writeln!(out, "// Code generated by e2e-generator. DO NOT EDIT.").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "package io.github.treesitter.languagepack.e2e;").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "import static org.junit.jupiter.api.Assertions.*;").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "import io.github.treesitter.languagepack.TsPackRegistry;").unwrap();
    writeln!(out, "import org.junit.jupiter.api.Test;").unwrap();
    if needs_json {
        writeln!(out).unwrap();
        writeln!(out, "import com.google.gson.Gson;").unwrap();
        writeln!(out, "import com.google.gson.JsonObject;").unwrap();
        writeln!(out, "import com.google.gson.JsonArray;").unwrap();
    }
    writeln!(out).unwrap();
    writeln!(out, "class {class_name}Test {{").unwrap();
    if needs_json {
        writeln!(out).unwrap();
        writeln!(out, "    private static final Gson GSON = new Gson();").unwrap();
    }
    writeln!(out).unwrap();

    for fixture in fixtures {
        let method_name = sanitize_name(&fixture.id);
        let assertions = fixture.assertions.as_ref();

        writeln!(out, "    @Test").unwrap();
        writeln!(out, "    void {method_name}() {{").unwrap();
        writeln!(out, "        // {}", fixture.description).unwrap();

        // Skip logic (using Assumptions in JUnit 5)
        if let Some(skip) = &fixture.skip
            && let Some(req_lang) = &skip.requires_language
        {
            writeln!(out, "        try (var registry = Helpers.createRegistry()) {{").unwrap();
            writeln!(
                    out,
                    "            org.junit.jupiter.api.Assumptions.assumeTrue(registry.hasLanguage(\"{}\"), \"Language '{}' not available\");",
                    escape_java_string(req_lang),
                    escape_java_string(req_lang)
                )
                .unwrap();
            writeln!(out, "        }}").unwrap();
        }

        if assertions.is_some_and(|a| a.expect_error == Some(true)) {
            if let Some(lang) = &fixture.language {
                writeln!(out, "        try (var registry = Helpers.createRegistry()) {{").unwrap();
                writeln!(
                    out,
                    "            assertThrows(Exception.class, () -> registry.getLanguage(\"{}\"));",
                    escape_java_string(lang)
                )
                .unwrap();
                writeln!(out, "        }}").unwrap();
            }
        } else if assertions.is_some_and(|a| a.languages_not_empty == Some(true)) {
            writeln!(out, "        try (var registry = Helpers.createRegistry()) {{").unwrap();
            writeln!(
                out,
                "            assertFalse(registry.availableLanguages().isEmpty(), \"availableLanguages() should not be empty\");"
            )
            .unwrap();
            writeln!(out, "        }}").unwrap();
        } else if assertions.is_some_and(|a| a.language_available.is_some()) {
            let expected = assertions.unwrap().language_available.unwrap();
            let lang = fixture.language.as_deref().unwrap_or("unknown");
            writeln!(out, "        try (var registry = Helpers.createRegistry()) {{").unwrap();
            writeln!(
                out,
                "            assertEquals({expected}, registry.hasLanguage(\"{}\"));",
                escape_java_string(lang)
            )
            .unwrap();
            writeln!(out, "        }}").unwrap();
        } else if has_intel_assertions(fixture) {
            let lang = fixture.language.as_deref().unwrap_or("unknown");
            let source = fixture.source_code.as_deref().unwrap_or("");
            let assertions = assertions.unwrap();

            writeln!(out, "        try (var registry = Helpers.createRegistry()) {{").unwrap();

            if has_chunk_assertions(fixture) {
                let max_chunk_size = assertions.intel_chunk_max_size.unwrap_or(512);
                writeln!(
                    out,
                    "            String resultJson = registry.processAndChunk(\"{}\", \"{}\", {});",
                    escape_java_string(source),
                    escape_java_string(lang),
                    max_chunk_size
                )
                .unwrap();
            } else {
                writeln!(
                    out,
                    "            String resultJson = registry.process(\"{}\", \"{}\");",
                    escape_java_string(source),
                    escape_java_string(lang)
                )
                .unwrap();
            }

            writeln!(
                out,
                "            JsonObject intel = GSON.fromJson(resultJson, JsonObject.class);"
            )
            .unwrap();

            if has_chunk_assertions(fixture) {
                if let Some(min_chunks) = assertions.intel_chunk_count_min {
                    writeln!(out, "            JsonArray chunks = intel.getAsJsonArray(\"chunks\");").unwrap();
                    writeln!(
                        out,
                        "            assertTrue(chunks.size() >= {}, \"Should have at least {} chunk(s), got \" + chunks.size());",
                        min_chunks,
                        min_chunks
                    )
                    .unwrap();
                }
                writeln!(out, "            intel = intel.getAsJsonObject(\"intelligence\");").unwrap();
            }

            if let Some(expected_lang) = &assertions.intel_language {
                writeln!(
                    out,
                    "            assertEquals(\"{}\", intel.get(\"language\").getAsString());",
                    escape_java_string(expected_lang)
                )
                .unwrap();
            }

            if let Some(min_structures) = assertions.intel_structure_count_min {
                writeln!(
                    out,
                    "            assertTrue(intel.getAsJsonArray(\"structure\").size() >= {}, \"Should have at least {} structure(s)\");",
                    min_structures,
                    min_structures
                )
                .unwrap();
            }

            if let Some(expected_kind) = &assertions.intel_structure_contains_kind {
                writeln!(out, "            boolean foundKind = false;").unwrap();
                writeln!(
                    out,
                    "            for (var elem : intel.getAsJsonArray(\"structure\")) {{"
                )
                .unwrap();
                writeln!(
                    out,
                    "                if (elem.getAsJsonObject().get(\"kind\").getAsString().equals(\"{}\")) {{",
                    escape_java_string(expected_kind)
                )
                .unwrap();
                writeln!(out, "                    foundKind = true;").unwrap();
                writeln!(out, "                    break;").unwrap();
                writeln!(out, "                }}").unwrap();
                writeln!(out, "            }}").unwrap();
                writeln!(
                    out,
                    "            assertTrue(foundKind, \"Structure should contain a '{}' kind node\");",
                    escape_java_string(expected_kind)
                )
                .unwrap();
            }

            if let Some(min_imports) = assertions.intel_imports_count_min {
                writeln!(
                    out,
                    "            assertTrue(intel.getAsJsonArray(\"imports\").size() >= {}, \"Should have at least {} import(s)\");",
                    min_imports,
                    min_imports
                )
                .unwrap();
            }

            if let Some(min_lines) = assertions.intel_metrics_total_lines_min {
                writeln!(
                    out,
                    "            JsonObject metrics = intel.getAsJsonObject(\"metrics\");"
                )
                .unwrap();
                writeln!(
                    out,
                    "            assertTrue(metrics.get(\"total_lines\").getAsInt() >= {}, \"Should have at least {} total line(s)\");",
                    min_lines,
                    min_lines
                )
                .unwrap();
            }

            if let Some(expected_error_count) = assertions.intel_metrics_error_count {
                writeln!(
                    out,
                    "            JsonObject metricsObj = intel.getAsJsonObject(\"metrics\");"
                )
                .unwrap();
                writeln!(
                    out,
                    "            assertEquals({}, metricsObj.get(\"error_count\").getAsInt(), \"Expected error_count {}\");",
                    expected_error_count,
                    expected_error_count
                )
                .unwrap();
            }

            if assertions.intel_diagnostics_not_empty == Some(true) {
                writeln!(
                    out,
                    "            assertFalse(intel.getAsJsonArray(\"diagnostics\").isEmpty(), \"Diagnostics should not be empty\");"
                )
                .unwrap();
            }

            writeln!(out, "        }}").unwrap();
        } else if let Some(lang) = &fixture.language {
            writeln!(out, "        try (var registry = Helpers.createRegistry()) {{").unwrap();
            writeln!(
                out,
                "            var langPtr = registry.getLanguage(\"{}\");",
                escape_java_string(lang)
            )
            .unwrap();
            writeln!(
                out,
                "            assertNotNull(langPtr, \"Language pointer should not be null\");"
            )
            .unwrap();
            writeln!(out, "        }}").unwrap();
        }

        writeln!(out, "    }}").unwrap();
        writeln!(out).unwrap();
    }

    writeln!(out, "}}").unwrap();

    let filename = format!("{class_name}Test.java");
    std::fs::write(pkg_dir.join(&filename), &out).map_err(|e| format!("Failed to write {filename}: {e}"))
}

/// Convert a category name to a Java PascalCase class name.
fn to_java_class_name(category: &str) -> String {
    let sanitized = sanitize_name(category);
    let mut result = String::new();
    let mut capitalize_next = true;

    for c in sanitized.chars() {
        if c == '_' {
            capitalize_next = true;
        } else if capitalize_next {
            result.push(c.to_ascii_uppercase());
            capitalize_next = false;
        } else {
            result.push(c);
        }
    }

    result
}
