use crate::fixtures::{Fixture, escape_python_string, group_by_category, sanitize_name};
use crate::generators::Generator;
use std::fmt::Write as FmtWrite;
use std::path::Path;

pub struct PythonGenerator;

impl Generator for PythonGenerator {
    fn name(&self) -> &'static str {
        "Python"
    }

    fn generate(&self, fixtures: &[Fixture], output_dir: &Path) -> Result<(), String> {
        let py_dir = output_dir.join("python");
        std::fs::create_dir_all(py_dir.join("tests"))
            .map_err(|e| format!("Failed to create python output dir: {e}"))?;

        write_pyproject_toml(&py_dir)?;
        write_init_py(&py_dir)?;
        write_helpers_py(&py_dir)?;

        let groups = group_by_category(fixtures);
        for (category, cat_fixtures) in &groups {
            write_test_file(&py_dir, category, cat_fixtures)?;
        }

        Ok(())
    }
}

fn write_pyproject_toml(dir: &Path) -> Result<(), String> {
    let content = r#"# Code generated by e2e-generator. DO NOT EDIT.

[project]
name = "e2e-tests"
version = "0.0.0"
requires-python = ">=3.10"
dependencies = [
    "tree-sitter-language-pack",
    "pytest",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
"#;
    std::fs::write(dir.join("pyproject.toml"), content).map_err(|e| format!("Failed to write pyproject.toml: {e}"))
}

fn write_init_py(dir: &Path) -> Result<(), String> {
    std::fs::write(dir.join("tests").join("__init__.py"), "").map_err(|e| format!("Failed to write __init__.py: {e}"))
}

fn write_helpers_py(dir: &Path) -> Result<(), String> {
    let content = r#"# Code generated by e2e-generator. DO NOT EDIT.


def tree_contains_node_type(node, node_type: str) -> bool:
    """Check whether a tree-sitter node or any descendant has the given type."""
    if node.type == node_type:
        return True
    for child in node.children:
        if tree_contains_node_type(child, node_type):
            return True
    return False


def tree_has_error_nodes(node) -> bool:
    """Check whether a tree-sitter node or any descendant is an ERROR node."""
    if node.type == "ERROR" or node.is_missing:
        return True
    for child in node.children:
        if tree_has_error_nodes(child):
            return True
    return False
"#;
    std::fs::write(dir.join("tests").join("helpers.py"), content)
        .map_err(|e| format!("Failed to write helpers.py: {e}"))
}

fn has_intel_assertions(fixture: &Fixture) -> bool {
    fixture.assertions.as_ref().is_some_and(|a| {
        a.intel_language.is_some()
            || a.intel_structure_count_min.is_some()
            || a.intel_structure_contains_kind.is_some()
            || a.intel_imports_count_min.is_some()
            || a.intel_metrics_total_lines_min.is_some()
            || a.intel_metrics_error_count.is_some()
            || a.intel_diagnostics_not_empty.is_some()
            || a.intel_chunk_count_min.is_some()
    })
}

fn has_chunk_assertions(fixture: &Fixture) -> bool {
    fixture
        .assertions
        .as_ref()
        .is_some_and(|a| a.intel_chunk_count_min.is_some())
}

fn write_test_file(dir: &Path, category: &str, fixtures: &[&Fixture]) -> Result<(), String> {
    let mut out = String::new();

    writeln!(out, "# Code generated by e2e-generator. DO NOT EDIT.").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "import pytest").unwrap();
    writeln!(out, "import json").unwrap();
    writeln!(out).unwrap();
    writeln!(
        out,
        "from tree_sitter_language_pack import get_language, get_parser, available_languages, has_language, process, process_and_chunk"
    )
    .unwrap();
    writeln!(out).unwrap();
    writeln!(
        out,
        "from .helpers import tree_contains_node_type, tree_has_error_nodes"
    )
    .unwrap();
    writeln!(out).unwrap();
    writeln!(out).unwrap();

    for fixture in fixtures {
        let fn_name = sanitize_name(&fixture.id);
        let assertions = fixture.assertions.as_ref();

        // Skip decorator
        if let Some(skip) = &fixture.skip
            && let Some(req_lang) = &skip.requires_language
        {
            writeln!(
                out,
                "@pytest.mark.skipif(not has_language(\"{req_lang}\"), reason=\"Language '{req_lang}' not available\")"
            )
            .unwrap();
        }

        writeln!(out, "def test_{fn_name}():").unwrap();
        writeln!(out, "    \"\"\"{}\"\"\"", fixture.description).unwrap();

        if assertions.is_some_and(|a| a.expect_error == Some(true)) {
            if let Some(lang) = &fixture.language {
                writeln!(
                    out,
                    "    with pytest.raises(Exception):\n        get_language(\"{}\")",
                    escape_python_string(lang)
                )
                .unwrap();
            }
        } else if assertions.is_some_and(|a| a.languages_not_empty == Some(true)) {
            writeln!(out, "    langs = available_languages()").unwrap();
            writeln!(
                out,
                "    assert len(langs) > 0, \"available_languages() should not be empty\""
            )
            .unwrap();
        } else if assertions.is_some_and(|a| a.language_available.is_some()) {
            let expected = assertions.unwrap().language_available.unwrap();
            let lang = fixture.language.as_deref().unwrap_or("unknown");
            writeln!(
                out,
                "    assert has_language(\"{}\") is {}, \"has_language('{}') should be {}\"",
                escape_python_string(lang),
                if expected { "True" } else { "False" },
                escape_python_string(lang),
                expected
            )
            .unwrap();
        } else if has_intel_assertions(fixture) {
            let lang = fixture.language.as_deref().unwrap_or("unknown");
            let source = fixture.source_code.as_deref().unwrap_or("");
            let assertions = assertions.unwrap();

            if has_chunk_assertions(fixture) {
                if let Some(max_chunk_size) = assertions.intel_chunk_count_min {
                    writeln!(
                        out,
                        "    result_json = process_and_chunk(\"{}\", \"{}\", {})",
                        escape_python_string(source),
                        escape_python_string(lang),
                        max_chunk_size
                    )
                    .unwrap();
                }
            } else {
                writeln!(
                    out,
                    "    result_json = process(\"{}\", \"{}\")",
                    escape_python_string(source),
                    escape_python_string(lang)
                )
                .unwrap();
            }

            writeln!(out, "    intel = json.loads(result_json)").unwrap();

            if has_chunk_assertions(fixture) {
                if let Some(min_chunks) = assertions.intel_chunk_count_min {
                    writeln!(out, "    chunks = intel.get(\"chunks\", [])").unwrap();
                    writeln!(
                        out,
                        "    assert len(chunks) >= {min_chunks}, f\"Should have at least {min_chunks} chunk(s), got {{len(chunks)}}\""
                    )
                    .unwrap();
                }
                writeln!(out, "    intel = intel.get(\"intelligence\", {{}})").unwrap();
            }

            if let Some(expected_lang) = &assertions.intel_language {
                writeln!(
                    out,
                    "    assert intel.get(\"language\") == \"{}\", f\"Expected language '{}', got {{intel.get('language')}}\"",
                    escape_python_string(expected_lang),
                    escape_python_string(expected_lang)
                )
                .unwrap();
            }

            if let Some(min_structures) = assertions.intel_structure_count_min {
                writeln!(
                    out,
                    "    assert len(intel.get(\"structure\", [])) >= {min_structures}, f\"Should have at least {min_structures} structure(s)\""
                )
                .unwrap();
            }

            if let Some(expected_kind) = &assertions.intel_structure_contains_kind {
                writeln!(
                    out,
                    "    assert any(s.get(\"kind\") == \"{}\" for s in intel.get(\"structure\", [])), f\"Structure should contain a '{}' kind node\"",
                    escape_python_string(expected_kind),
                    escape_python_string(expected_kind)
                )
                .unwrap();
            }

            if let Some(min_imports) = assertions.intel_imports_count_min {
                writeln!(
                    out,
                    "    assert len(intel.get(\"imports\", [])) >= {min_imports}, f\"Should have at least {min_imports} import(s)\""
                )
                .unwrap();
            }

            if let Some(min_lines) = assertions.intel_metrics_total_lines_min {
                writeln!(out, "    metrics = intel.get(\"metrics\", {{}})").unwrap();
                writeln!(
                    out,
                    "    assert metrics.get(\"total_lines\", 0) >= {min_lines}, f\"Should have at least {min_lines} total line(s)\""
                )
                .unwrap();
            }

            if let Some(expected_error_count) = assertions.intel_metrics_error_count {
                writeln!(out, "    metrics = intel.get(\"metrics\", {{}})").unwrap();
                writeln!(
                    out,
                    "    assert metrics.get(\"error_count\", 0) == {expected_error_count}, f\"Expected error_count {expected_error_count}, got {{metrics.get('error_count', 0)}}\""
                )
                .unwrap();
            }

            if assertions.intel_diagnostics_not_empty == Some(true) {
                writeln!(
                    out,
                    "    assert len(intel.get(\"diagnostics\", [])) > 0, \"Diagnostics should not be empty\""
                )
                .unwrap();
            }
        } else if let Some(lang) = &fixture.language {
            let source = fixture.source_code.as_deref().unwrap_or("");
            writeln!(out, "    parser = get_parser(\"{}\")", escape_python_string(lang)).unwrap();
            writeln!(out, "    tree = parser.parse(b\"{}\")", escape_python_string(source)).unwrap();

            if assertions.is_some_and(|a| a.tree_not_null == Some(true)) {
                writeln!(out, "    assert tree is not None, \"Parse tree should not be None\"").unwrap();
                writeln!(out, "    root = tree.root_node").unwrap();

                if let Some(min_children) = assertions.and_then(|a| a.root_child_count_min) {
                    writeln!(
                        out,
                        "    assert root.child_count >= {min_children}, f\"Root should have at least {min_children} child(ren), got {{root.child_count}}\""
                    )
                    .unwrap();
                }

                if let Some(node_type) = assertions.and_then(|a| a.root_contains_node_type.as_deref()) {
                    writeln!(
                        out,
                        "    assert tree_contains_node_type(root, \"{}\"), \"Tree should contain a '{}' node\"",
                        escape_python_string(node_type),
                        escape_python_string(node_type)
                    )
                    .unwrap();
                }

                if assertions.is_some_and(|a| a.has_error_nodes == Some(true)) {
                    writeln!(
                        out,
                        "    assert tree_has_error_nodes(root), \"Tree should contain error nodes\""
                    )
                    .unwrap();
                }
            }
        }

        writeln!(out).unwrap();
        writeln!(out).unwrap();
    }

    let filename = format!("test_{}.py", sanitize_name(category));
    std::fs::write(dir.join("tests").join(&filename), &out).map_err(|e| format!("Failed to write {filename}: {e}"))
}
