use crate::fixtures::{
    Fixture, escape_rust_string, group_by_category, has_chunk_assertions, has_intel_assertions, sanitize_name,
};
use crate::generators::Generator;
use std::fmt::Write as FmtWrite;
use std::path::Path;

pub struct RustGenerator;

impl Generator for RustGenerator {
    fn name(&self) -> &'static str {
        "Rust"
    }

    fn generate(&self, fixtures: &[Fixture], output_dir: &Path) -> Result<(), String> {
        let rust_dir = output_dir.join("rust");

        // Clean stale test files before writing new ones
        let _ = std::fs::remove_dir_all(&rust_dir);

        std::fs::create_dir_all(rust_dir.join("src")).map_err(|e| format!("Failed to create rust output dir: {e}"))?;
        std::fs::create_dir_all(rust_dir.join("tests")).map_err(|e| format!("Failed to create rust tests dir: {e}"))?;

        write_cargo_toml(&rust_dir)?;
        write_lib_rs(&rust_dir)?;

        let groups = group_by_category(fixtures);
        for (category, cat_fixtures) in &groups {
            write_test_file(&rust_dir, category, cat_fixtures)?;
        }

        // Run cargo fmt if available
        let _ = std::process::Command::new("cargo")
            .args(["fmt", "--manifest-path"])
            .arg(rust_dir.join("Cargo.toml"))
            .status();

        Ok(())
    }
}

fn write_cargo_toml(dir: &Path) -> Result<(), String> {
    let content = r#"# Code generated by e2e-generator. DO NOT EDIT.

[package]
name = "e2e-tests"
version = "0.0.0"
edition = "2024"
publish = false

[lib]
doctest = false

[workspace]

[workspace.dependencies]
ts-pack-core = { path = "../../crates/ts-pack-core", features = ["serde", "all"] }
tree-sitter = "0.26"
serde_json = "1"

[dependencies]
ts-pack-core = { workspace = true }
tree-sitter = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
ts-pack-core = { workspace = true }
tree-sitter = { workspace = true }
serde_json = { workspace = true }
"#;
    std::fs::write(dir.join("Cargo.toml"), content).map_err(|e| format!("Failed to write Cargo.toml: {e}"))
}

fn write_lib_rs(dir: &Path) -> Result<(), String> {
    let content = r#"// Code generated by e2e-generator. DO NOT EDIT.
#![allow(clippy::too_many_lines)]

/// Check whether a tree-sitter node or any of its descendants has the given type.
pub fn tree_contains_node_type(node: tree_sitter::Node, node_type: &str) -> bool {
    if node.kind() == node_type {
        return true;
    }
    let mut cursor = node.walk();
    for child in node.children(&mut cursor) {
        if tree_contains_node_type(child, node_type) {
            return true;
        }
    }
    false
}

/// Check whether a tree-sitter node or any of its descendants is an ERROR node.
pub fn tree_has_error_nodes(node: tree_sitter::Node) -> bool {
    if node.is_error() || node.is_missing() {
        return true;
    }
    let mut cursor = node.walk();
    for child in node.children(&mut cursor) {
        if tree_has_error_nodes(child) {
            return true;
        }
    }
    false
}
"#;
    std::fs::write(dir.join("src").join("lib.rs"), content).map_err(|e| format!("Failed to write lib.rs: {e}"))
}

/// Map a fixture kind string to a Rust StructureKind variant expression.
fn structure_kind_variant(kind: &str) -> String {
    match kind.to_ascii_lowercase().as_str() {
        "function" => "ts_pack_core::StructureKind::Function".to_string(),
        "method" => "ts_pack_core::StructureKind::Method".to_string(),
        "class" => "ts_pack_core::StructureKind::Class".to_string(),
        "struct" => "ts_pack_core::StructureKind::Struct".to_string(),
        "interface" => "ts_pack_core::StructureKind::Interface".to_string(),
        "enum" => "ts_pack_core::StructureKind::Enum".to_string(),
        "module" => "ts_pack_core::StructureKind::Module".to_string(),
        "trait" => "ts_pack_core::StructureKind::Trait".to_string(),
        "impl" => "ts_pack_core::StructureKind::Impl".to_string(),
        "namespace" => "ts_pack_core::StructureKind::Namespace".to_string(),
        _ => format!(
            "ts_pack_core::StructureKind::Other(\"{}\".to_string())",
            escape_rust_string(kind)
        ),
    }
}

/// Write intel assertion code for a fixture.
fn write_intel_assertions(out: &mut String, fixture: &Fixture) {
    let assertions = fixture.assertions.as_ref().unwrap();
    let lang = fixture.language.as_deref().unwrap_or("unknown");
    let source = fixture.source_code.as_deref().unwrap_or("");

    writeln!(out, "    // {}", fixture.description).unwrap();
    writeln!(out, "    let registry = ts_pack_core::LanguageRegistry::new();").unwrap();

    if has_chunk_assertions(fixture) {
        let max_size = assertions.intel_chunk_max_size.unwrap_or(1000);
        writeln!(
            out,
            "    let (intel, chunks) = registry.process_and_chunk(\"{}\", \"{}\", {}).expect(\"process_and_chunk failed\");",
            escape_rust_string(source),
            escape_rust_string(lang),
            max_size
        )
        .unwrap();

        // Chunk assertions
        if let Some(min_chunks) = assertions.intel_chunk_count_min {
            writeln!(
                out,
                "    assert!(chunks.len() >= {min_chunks}, \"Expected at least {min_chunks} chunk(s), got {{}}\", chunks.len());"
            )
            .unwrap();
        }
    } else {
        writeln!(
            out,
            "    let intel = registry.process(\"{}\", \"{}\").expect(\"process failed\");",
            escape_rust_string(source),
            escape_rust_string(lang)
        )
        .unwrap();
    }

    // Intel field assertions
    if let Some(expected_lang) = &assertions.intel_language {
        writeln!(
            out,
            "    assert_eq!(intel.language, \"{}\", \"intel.language mismatch\");",
            escape_rust_string(expected_lang)
        )
        .unwrap();
    }

    if let Some(min_count) = assertions.intel_structure_count_min {
        writeln!(
            out,
            "    assert!(intel.structure.len() >= {min_count}, \"Expected at least {min_count} structure item(s), got {{}}\", intel.structure.len());"
        )
        .unwrap();
    }

    if let Some(kind) = &assertions.intel_structure_contains_kind {
        let variant = structure_kind_variant(kind);
        writeln!(
            out,
            "    assert!(intel.structure.iter().any(|s| s.kind == {variant}), \"Structure should contain a '{}' item\");",
            escape_rust_string(kind)
        )
        .unwrap();
    }

    if let Some(min_imports) = assertions.intel_imports_count_min {
        writeln!(
            out,
            "    assert!(intel.imports.len() >= {min_imports}, \"Expected at least {min_imports} import(s), got {{}}\", intel.imports.len());"
        )
        .unwrap();
    }

    if let Some(min_lines) = assertions.intel_metrics_total_lines_min {
        writeln!(
            out,
            "    assert!(intel.metrics.total_lines >= {min_lines}, \"Expected at least {min_lines} total line(s), got {{}}\", intel.metrics.total_lines);"
        )
        .unwrap();
    }

    if let Some(expected_errors) = assertions.intel_metrics_error_count {
        writeln!(
            out,
            "    assert_eq!(intel.metrics.error_count, {expected_errors}, \"Expected error_count == {expected_errors}, got {{}}\", intel.metrics.error_count);"
        )
        .unwrap();
    }

    if assertions.intel_diagnostics_not_empty == Some(true) {
        writeln!(
            out,
            "    assert!(!intel.diagnostics.is_empty(), \"diagnostics should not be empty\");"
        )
        .unwrap();
    }
}

fn write_test_file(dir: &Path, category: &str, fixtures: &[&Fixture]) -> Result<(), String> {
    let mut out = String::new();

    writeln!(out, "// Code generated by e2e-generator. DO NOT EDIT.").unwrap();
    writeln!(out, "#![allow(clippy::too_many_lines)]").unwrap();
    writeln!(out).unwrap();

    for fixture in fixtures {
        let fn_name = sanitize_name(&fixture.id);
        writeln!(out, "#[test]").unwrap();
        writeln!(out, "fn {fn_name}() {{").unwrap();

        // Auto-skip: guard any test that requires a specific language to be available.
        // Explicit skip.requires_language takes precedence; otherwise infer from fixture.language.
        let assertions = fixture.assertions.as_ref();
        let is_availability_agnostic = assertions.is_some_and(|a| {
            a.expect_error == Some(true) || a.language_available.is_some() || a.languages_not_empty == Some(true)
        });
        let skip_lang = fixture.skip.as_ref().and_then(|s| s.requires_language.as_deref()).or({
            if !is_availability_agnostic {
                fixture.language.as_deref()
            } else {
                None
            }
        });
        if let Some(req_lang) = skip_lang {
            writeln!(out, "    if !ts_pack_core::has_language(\"{req_lang}\") {{").unwrap();
            writeln!(
                out,
                "        eprintln!(\"Skipping: language '{}' not available\");",
                req_lang
            )
            .unwrap();
            writeln!(out, "        return;").unwrap();
            writeln!(out, "    }}").unwrap();
        }

        // Check if this is an expect_error test
        if assertions.is_some_and(|a| a.expect_error == Some(true)) {
            if let Some(lang) = &fixture.language {
                writeln!(
                    out,
                    "    // {}\n    let result = ts_pack_core::get_language(\"{}\");",
                    fixture.description,
                    escape_rust_string(lang)
                )
                .unwrap();
                writeln!(
                    out,
                    "    assert!(result.is_err(), \"Expected error loading language '{}'\");",
                    escape_rust_string(lang)
                )
                .unwrap();
            }
        } else if assertions.is_some_and(|a| a.languages_not_empty == Some(true)) {
            // Registry: list languages
            writeln!(out, "    // {}", fixture.description).unwrap();
            writeln!(out, "    let langs = ts_pack_core::available_languages();").unwrap();
            writeln!(
                out,
                "    assert!(!langs.is_empty(), \"available_languages() should not be empty\");"
            )
            .unwrap();
        } else if assertions.is_some_and(|a| a.language_available.is_some()) {
            // Registry: has_language
            let expected = assertions.unwrap().language_available.unwrap();
            let lang = fixture.language.as_deref().unwrap_or("unknown");
            writeln!(out, "    // {}", fixture.description).unwrap();
            writeln!(
                out,
                "    assert_eq!(ts_pack_core::has_language(\"{}\"), {expected});",
                escape_rust_string(lang)
            )
            .unwrap();
        } else if has_intel_assertions(fixture) {
            // Intel test: call process() or process_and_chunk()
            write_intel_assertions(&mut out, fixture);
        } else {
            // Parsing test
            if let Some(lang) = &fixture.language {
                writeln!(out, "    // {}", fixture.description).unwrap();
                writeln!(
                    out,
                    "    let mut parser = ts_pack_core::get_parser(\"{}\").expect(\"Failed to get parser for '{}'\");",
                    escape_rust_string(lang),
                    escape_rust_string(lang)
                )
                .unwrap();

                let source = fixture.source_code.as_deref().unwrap_or("");
                let has_tree_assertions = assertions.is_some_and(|a| a.tree_not_null == Some(true));
                let tree_binding = if has_tree_assertions { "tree" } else { "_tree" };
                writeln!(
                    out,
                    "    let {tree_binding} = parser.parse(\"{}\", None);",
                    escape_rust_string(source)
                )
                .unwrap();

                if has_tree_assertions {
                    writeln!(out, "    assert!(tree.is_some(), \"Parse tree should not be None\");").unwrap();

                    let needs_root = assertions.is_some_and(|a| {
                        a.root_child_count_min.is_some()
                            || a.root_contains_node_type.is_some()
                            || a.has_error_nodes == Some(true)
                    });
                    if needs_root {
                        writeln!(out, "    let tree = tree.unwrap();").unwrap();
                        writeln!(out, "    let root = tree.root_node();").unwrap();
                    }

                    if let Some(min_children) = assertions.and_then(|a| a.root_child_count_min) {
                        writeln!(
                            out,
                            "    assert!(root.child_count() >= {min_children}, \"Root should have at least {min_children} child(ren), got {{}}\", root.child_count());"
                        )
                        .unwrap();
                    }

                    if let Some(node_type) = assertions.and_then(|a| a.root_contains_node_type.as_deref()) {
                        writeln!(
                            out,
                            "    assert!(e2e_tests::tree_contains_node_type(root, \"{}\"), \"Tree should contain a '{}' node\");",
                            escape_rust_string(node_type),
                            escape_rust_string(node_type)
                        )
                        .unwrap();
                    }

                    if assertions.is_some_and(|a| a.has_error_nodes == Some(true)) {
                        writeln!(
                            out,
                            "    assert!(e2e_tests::tree_has_error_nodes(root), \"Tree should contain error nodes\");"
                        )
                        .unwrap();
                    }
                }
            }
        }

        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();
    }

    // Trim trailing whitespace — rustfmt doesn't want trailing blank lines
    let out = out.trim_end().to_string() + "\n";

    let filename = format!("test_{}.rs", sanitize_name(category));
    std::fs::write(dir.join("tests").join(&filename), &out).map_err(|e| format!("Failed to write {filename}: {e}"))
}
