// Code generated by e2e-generator. DO NOT EDIT.

package e2e_tests

import "testing"

func TestErrorEmptyLanguageName(t *testing.T) {
	// Parsing with empty language name should error
	reg := newTestRegistry(t)
	_, err := reg.GetLanguage("")
	if err == nil {
		t.Fatalf("Expected error loading language %q, got nil", "")
	}
}

func TestErrorHandlingEmptySource(t *testing.T) {
	// Parsing an empty string should still produce a tree.
	reg := newTestRegistry(t)
	skipIfLanguageUnavailable(t, reg, "javascript")
	ptr, err := reg.GetLanguage("javascript")
	if err != nil {
		t.Fatalf("Failed to get language %q: %v", "javascript", err)
	}
	if ptr == nil {
		t.Fatalf("Language pointer for %q is nil", "javascript")
	}
}

func TestErrorHandlingInvalidSyntax(t *testing.T) {
	// Parsing invalid syntax should produce a tree with error nodes.
	reg := newTestRegistry(t)
	skipIfLanguageUnavailable(t, reg, "javascript")
	ptr, err := reg.GetLanguage("javascript")
	if err != nil {
		t.Fatalf("Failed to get language %q: %v", "javascript", err)
	}
	if ptr == nil {
		t.Fatalf("Language pointer for %q is nil", "javascript")
	}
}

func TestErrorHandlingUnknownLanguage(t *testing.T) {
	// Loading a nonexistent language should produce an error.
	reg := newTestRegistry(t)
	_, err := reg.GetLanguage("nonexistent_xyz")
	if err == nil {
		t.Fatalf("Expected error loading language %q, got nil", "nonexistent_xyz")
	}
}
