// Code generated by e2e-generator. DO NOT EDIT.

module e2e_tests

go 1.22

require github.com/kreuzberg-dev/tree-sitter-language-pack/crates/ts-pack-go v0.0.0

replace github.com/kreuzberg-dev/tree-sitter-language-pack/crates/ts-pack-go => ../../crates/ts-pack-go
