// Code generated by e2e-generator. DO NOT EDIT.

module e2e_tests

go 1.26

require github.com/kreuzberg-dev/tree-sitter-language-pack/packages/go v0.0.0

replace github.com/kreuzberg-dev/tree-sitter-language-pack/packages/go => ../../packages/go/v1
