// Code generated by e2e-generator. DO NOT EDIT.

package e2e_tests

import (
	"testing"

	tspack "github.com/kreuzberg-dev/tree-sitter-language-pack/packages/go"
)

// newTestRegistry creates a registry for testing and registers cleanup.
func newTestRegistry(t *testing.T) *tspack.Registry {
	t.Helper()

	reg, err := tspack.NewRegistry()
	if err != nil {
		t.Fatalf("Failed to create registry: %v", err)
	}
	t.Cleanup(func() { reg.Close() })

	return reg
}

// skipIfLanguageUnavailable skips the test if the given language is not available.
func skipIfLanguageUnavailable(t *testing.T, reg *tspack.Registry, lang string) {
	t.Helper()

	if !reg.HasLanguage(lang) {
		t.Skipf("Language %q not available", lang)
	}
}
