// Code generated by e2e-generator. DO NOT EDIT.

package e2e_tests

import (
	"encoding/json"
	"testing"
)

func TestPythonChunkingIntel(t *testing.T) {
	// Intel: chunk multi-function Python source into multiple pieces
	reg := newTestRegistry(t)
	skipIfLanguageUnavailable(t, reg, "python")
	reg := newTestRegistry(t)
	resultJSON, err := reg.ProcessAndChunk("def alpha():\n    pass\n\ndef beta():\n    pass\n\ndef gamma():\n    pass\n\ndef delta():\n    pass\n", "python", 30)
	if err != nil {
		t.Fatalf("process failed: %v", err)
	}

	var intel map[string]interface{}
	if err := json.Unmarshal([]byte(resultJSON), &intel); err != nil {
		t.Fatalf("failed to unmarshal JSON: %v", err)
	}

	chunks, _ := intel["chunks"].([]interface{})
	if len(chunks) < 2 {
		t.Fatalf("expected at least 2 chunk(s), got %d", len(chunks))
	}
	if intelObj, ok := intel["intelligence"].(map[string]interface{}); ok {
		intel = intelObj
	}

	if lang, _ := intel["language"].(string); lang != "python" {
		t.Fatalf("expected language %q, got %q", "python", lang)
	}

	metrics, _ := intel["metrics"].(map[string]interface{})
	totalLines, _ := metrics["total_lines"].(float64)
	if int(totalLines) < 8 {
		t.Fatalf("expected at least 8 total line(s), got %v", totalLines)
	}
}

func TestPythonFunctionIntel(t *testing.T) {
	// Intel: extract structure from Python function definition
	reg := newTestRegistry(t)
	skipIfLanguageUnavailable(t, reg, "python")
	reg := newTestRegistry(t)
	resultJSON, err := reg.Process("def greet(name):\n    return f'Hello, {name}!'\n", "python")
	if err != nil {
		t.Fatalf("process failed: %v", err)
	}

	var intel map[string]interface{}
	if err := json.Unmarshal([]byte(resultJSON), &intel); err != nil {
		t.Fatalf("failed to unmarshal JSON: %v", err)
	}

	if lang, _ := intel["language"].(string); lang != "python" {
		t.Fatalf("expected language %q, got %q", "python", lang)
	}

	structure, _ := intel["structure"].([]interface{})
	if len(structure) < 1 {
		t.Fatalf("expected at least 1 structure(s), got %d", len(structure))
	}

	structureList, _ := intel["structure"].([]interface{})
	foundKind := false
	for _, s := range structureList {
		if m, ok := s.(map[string]interface{}); ok {
			if k, _ := m["kind"].(string); k == "function" {
				foundKind = true
				break
			}
		}
	}
	if !foundKind {
		t.Fatal("structure should contain a 'function' kind node")
	}

	metrics, _ := intel["metrics"].(map[string]interface{})
	totalLines, _ := metrics["total_lines"].(float64)
	if int(totalLines) < 2 {
		t.Fatalf("expected at least 2 total line(s), got %v", totalLines)
	}

	metricsMap, _ := intel["metrics"].(map[string]interface{})
	errorCount, _ := metricsMap["error_count"].(float64)
	if int(errorCount) != 0 {
		t.Fatalf("expected error_count 0, got %v", errorCount)
	}
}

func TestRustFunctionIntel(t *testing.T) {
	// Intel: extract structure from Rust function definition
	reg := newTestRegistry(t)
	skipIfLanguageUnavailable(t, reg, "rust")
	reg := newTestRegistry(t)
	resultJSON, err := reg.Process("fn add(a: i32, b: i32) -> i32 {\n    a + b\n}\n", "rust")
	if err != nil {
		t.Fatalf("process failed: %v", err)
	}

	var intel map[string]interface{}
	if err := json.Unmarshal([]byte(resultJSON), &intel); err != nil {
		t.Fatalf("failed to unmarshal JSON: %v", err)
	}

	if lang, _ := intel["language"].(string); lang != "rust" {
		t.Fatalf("expected language %q, got %q", "rust", lang)
	}

	structure, _ := intel["structure"].([]interface{})
	if len(structure) < 1 {
		t.Fatalf("expected at least 1 structure(s), got %d", len(structure))
	}

	structureList, _ := intel["structure"].([]interface{})
	foundKind := false
	for _, s := range structureList {
		if m, ok := s.(map[string]interface{}); ok {
			if k, _ := m["kind"].(string); k == "function" {
				foundKind = true
				break
			}
		}
	}
	if !foundKind {
		t.Fatal("structure should contain a 'function' kind node")
	}

	metrics, _ := intel["metrics"].(map[string]interface{})
	totalLines, _ := metrics["total_lines"].(float64)
	if int(totalLines) < 3 {
		t.Fatalf("expected at least 3 total line(s), got %v", totalLines)
	}

	metricsMap, _ := intel["metrics"].(map[string]interface{})
	errorCount, _ := metricsMap["error_count"].(float64)
	if int(errorCount) != 0 {
		t.Fatalf("expected error_count 0, got %v", errorCount)
	}
}

