// Code generated by e2e-generator. DO NOT EDIT.

package e2e_tests

import "testing"

func TestParsingGoFunction(t *testing.T) {
	// Parse a Go function declaration and assert node type
	reg := newTestRegistry(t)
	skipIfLanguageUnavailable(t, reg, "go")
	ptr, err := reg.GetLanguage("go")
	if err != nil {
		t.Fatalf("Failed to get language %q: %v", "go", err)
	}
	if ptr == nil {
		t.Fatalf("Language pointer for %q is nil", "go")
	}
}

func TestParsingHtmlElement(t *testing.T) {
	// Parse an HTML element and assert node type
	reg := newTestRegistry(t)
	skipIfLanguageUnavailable(t, reg, "html")
	ptr, err := reg.GetLanguage("html")
	if err != nil {
		t.Fatalf("Failed to get language %q: %v", "html", err)
	}
	if ptr == nil {
		t.Fatalf("Language pointer for %q is nil", "html")
	}
}

func TestParsingJavascriptClass(t *testing.T) {
	// Parse a JavaScript class declaration.
	reg := newTestRegistry(t)
	skipIfLanguageUnavailable(t, reg, "javascript")
	ptr, err := reg.GetLanguage("javascript")
	if err != nil {
		t.Fatalf("Failed to get language %q: %v", "javascript", err)
	}
	if ptr == nil {
		t.Fatalf("Language pointer for %q is nil", "javascript")
	}
}

func TestParsingJavascriptVariable(t *testing.T) {
	// Parse a JavaScript variable declaration and assert node type
	reg := newTestRegistry(t)
	skipIfLanguageUnavailable(t, reg, "javascript")
	ptr, err := reg.GetLanguage("javascript")
	if err != nil {
		t.Fatalf("Failed to get language %q: %v", "javascript", err)
	}
	if ptr == nil {
		t.Fatalf("Language pointer for %q is nil", "javascript")
	}
}

func TestParsingPythonFunction(t *testing.T) {
	// Parse a Python function definition and assert node type
	reg := newTestRegistry(t)
	skipIfLanguageUnavailable(t, reg, "python")
	ptr, err := reg.GetLanguage("python")
	if err != nil {
		t.Fatalf("Failed to get language %q: %v", "python", err)
	}
	if ptr == nil {
		t.Fatalf("Language pointer for %q is nil", "python")
	}
}

func TestParsingRustFunction(t *testing.T) {
	// Parse a Rust function definition and assert node type
	reg := newTestRegistry(t)
	skipIfLanguageUnavailable(t, reg, "rust")
	ptr, err := reg.GetLanguage("rust")
	if err != nil {
		t.Fatalf("Failed to get language %q: %v", "rust", err)
	}
	if ptr == nil {
		t.Fatalf("Language pointer for %q is nil", "rust")
	}
}

func TestParsingRustStruct(t *testing.T) {
	// Parse a Rust struct definition.
	reg := newTestRegistry(t)
	skipIfLanguageUnavailable(t, reg, "rust")
	ptr, err := reg.GetLanguage("rust")
	if err != nil {
		t.Fatalf("Failed to get language %q: %v", "rust", err)
	}
	if ptr == nil {
		t.Fatalf("Language pointer for %q is nil", "rust")
	}
}
