// Code generated by e2e-generator. DO NOT EDIT.

package e2e_tests

import "testing"

func TestTreeErrorCountBroken(t *testing.T) {
	// Parse broken Python code and verify error count >= 1
	reg := newTestRegistry(t)
	skipIfLanguageUnavailable(t, reg, "python")
	ptr, err := reg.GetLanguage("python")
	if err != nil {
		t.Fatalf("Failed to get language %q: %v", "python", err)
	}
	if ptr == nil {
		t.Fatalf("Language pointer for %q is nil", "python")
	}
}

func TestTreeErrorCountValid(t *testing.T) {
	// Parse valid Python code and verify zero error count
	reg := newTestRegistry(t)
	skipIfLanguageUnavailable(t, reg, "python")
	ptr, err := reg.GetLanguage("python")
	if err != nil {
		t.Fatalf("Failed to get language %q: %v", "python", err)
	}
	if ptr == nil {
		t.Fatalf("Language pointer for %q is nil", "python")
	}
}

func TestTreeFindNodesTwoFunctions(t *testing.T) {
	// Parse Python with 2 functions and verify find_nodes_by_type count
	reg := newTestRegistry(t)
	skipIfLanguageUnavailable(t, reg, "python")
	ptr, err := reg.GetLanguage("python")
	if err != nil {
		t.Fatalf("Failed to get language %q: %v", "python", err)
	}
	if ptr == nil {
		t.Fatalf("Language pointer for %q is nil", "python")
	}
}

func TestTreeNamedChildrenClassAndFunction(t *testing.T) {
	// Parse Python with class and function, verify named children count
	reg := newTestRegistry(t)
	skipIfLanguageUnavailable(t, reg, "python")
	ptr, err := reg.GetLanguage("python")
	if err != nil {
		t.Fatalf("Failed to get language %q: %v", "python", err)
	}
	if ptr == nil {
		t.Fatalf("Language pointer for %q is nil", "python")
	}
}

func TestTreeRootNodeInfoPython(t *testing.T) {
	// Parse Python source and verify root node info
	reg := newTestRegistry(t)
	skipIfLanguageUnavailable(t, reg, "python")
	ptr, err := reg.GetLanguage("python")
	if err != nil {
		t.Fatalf("Failed to get language %q: %v", "python", err)
	}
	if ptr == nil {
		t.Fatalf("Language pointer for %q is nil", "python")
	}
}
